/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const acceptInviteV1CampaignInvitesInviteIdAcceptPostPathParamsSchema = z.object({
    "invite_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const acceptInviteV1CampaignInvitesInviteIdAcceptPost204Schema = z.any()

/**
 * @description Invite not found, expired, or not addressed to you
 */
export const acceptInviteV1CampaignInvitesInviteIdAcceptPost404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const acceptInviteV1CampaignInvitesInviteIdAcceptPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const acceptInviteV1CampaignInvitesInviteIdAcceptPostMutationResponseSchema = z.lazy(() => acceptInviteV1CampaignInvitesInviteIdAcceptPost204Schema)
