/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to delete the current account.\n\nThe current password is required as a re-authentication step, so a\nstolen session alone cannot destroy the account. Deletion is\nirreversible.
 */
export const accountDeleteRequestSchema = z.object({
    "password": z.string().min(1).max(128).describe("The account's current password, for re-authentication.")
    }).describe("Payload to delete the current account.\n\nThe current password is required as a re-authentication step, so a\nstolen session alone cannot destroy the account. Deletion is\nirreversible.")
