/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description One of the user\'s owned books, with its content membership ids.\n\nContent is referenced by id rather than inlined: the export is a record\nof what the user has collected, not a copy of the SRD catalog.
 */
export const accountExportBookSchema = z.object({
    "id": z.uuid().describe("Unique identifier for the book."),
"name": z.string().describe("Display name of the book."),
"slug": z.nullable(z.string().describe("Stable handle for system books; null for user books.")),
"description": z.nullable(z.string().describe("Longer description, if any.")),
"isPublic": z.boolean().describe("Whether the book is readable by anyone."),
"isSystem": z.boolean().describe("Whether this is a read-only system book."),
"createdAt": z.iso.datetime().describe("When the book was created."),
"updatedAt": z.iso.datetime().describe("When the book was last updated."),
"monsterIds": z.array(z.uuid()).describe("Ids of the monsters collected in this book."),
"spellIds": z.array(z.uuid()).describe("Ids of the spells collected in this book."),
"itemIds": z.array(z.uuid()).describe("Ids of the items collected in this book.")
    }).describe("One of the user's owned books, with its content membership ids.\n\nContent is referenced by id rather than inlined: the export is a record\nof what the user has collected, not a copy of the SRD catalog.")
