/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { accountExportBookSchema } from "./accountExportBookSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description A portable copy of everything stored for the current account.
 */
export const accountExportSchema = z.object({
    "exportedAt": z.iso.datetime().describe("When this export was generated."),
get "account"(){
                return userResponseSchema.describe("The owner's own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.")
              },
get "books"(){
                return z.array(accountExportBookSchema.describe("One of the user's owned books, with its content membership ids.\n\nContent is referenced by id rather than inlined: the export is a record\nof what the user has collected, not a copy of the SRD catalog.")).describe("The books the account owns, with their content ids.")
              }
    }).describe("A portable copy of everything stored for the current account.")
