/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description An action-shaped entry (actions, special_abilities, legendary, reactions).\n\nWe render `name` + `desc`; everything else (damage, dc, usage,\nattack_bonus, ...) flows through via extra=\'allow\'.
 */
export const actionEntrySchema = z.object({
    "name": z.string(),
"desc": z.string()
    }).catchall(z.any()).describe("An action-shaped entry (actions, special_abilities, legendary, reactions).\n\nWe render `name` + `desc`; everything else (damage, dc, usage,\nattack_bonus, ...) flows through via extra='allow'.")
