/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const addBookSpellV1BooksBookIdSpellsSpellIdPutPathParamsSchema = z.object({
    "book_id": z.uuid(),
"spell_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const addBookSpellV1BooksBookIdSpellsSpellIdPut204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const addBookSpellV1BooksBookIdSpellsSpellIdPut403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book or content not found
 */
export const addBookSpellV1BooksBookIdSpellsSpellIdPut404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const addBookSpellV1BooksBookIdSpellsSpellIdPut422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const addBookSpellV1BooksBookIdSpellsSpellIdPutMutationResponseSchema = z.lazy(() => addBookSpellV1BooksBookIdSpellsSpellIdPut204Schema)
