/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const addBookItemV1BooksBookIdItemsItemIdPutPathParamsSchema = z.object({
    "book_id": z.uuid(),
"item_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const addBookItemV1BooksBookIdItemsItemIdPut204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const addBookItemV1BooksBookIdItemsItemIdPut403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book or content not found
 */
export const addBookItemV1BooksBookIdItemsItemIdPut404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const addBookItemV1BooksBookIdItemsItemIdPut422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const addBookItemV1BooksBookIdItemsItemIdPutMutationResponseSchema = z.lazy(() => addBookItemV1BooksBookIdItemsItemIdPut204Schema)
