/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const addBookMonsterV1BooksBookIdMonstersMonsterIdPutPathParamsSchema = z.object({
    "book_id": z.uuid(),
"monster_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const addBookMonsterV1BooksBookIdMonstersMonsterIdPut204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const addBookMonsterV1BooksBookIdMonstersMonsterIdPut403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book or content not found
 */
export const addBookMonsterV1BooksBookIdMonstersMonsterIdPut404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const addBookMonsterV1BooksBookIdMonstersMonsterIdPut422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const addBookMonsterV1BooksBookIdMonstersMonsterIdPutMutationResponseSchema = z.lazy(() => addBookMonsterV1BooksBookIdMonstersMonsterIdPut204Schema)
