/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Armor\'s base AC plus Dex-bonus rules.
 */
export const armorClassSchema = z.object({
    "base": z.int(),
"dexBonus": z.boolean(),
"maxBonus": z.int().nullish()
    }).catchall(z.any()).describe("Armor's base AC plus Dex-bonus rules.")
