/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description One element of the AC array (monsters carry multiple AC sources).
 */
export const armorClassEntrySchema = z.object({
    "type": z.string(),
"value": z.int(),
"condition": z.string().nullish()
    }).catchall(z.any()).describe("One element of the AC array (monsters carry multiple AC sources).")
