/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authorSchema } from "./authorSchema.ts";
import { z } from "zod/v4";

/**
 * @description A single book with the count of content it holds, by resource type.
 */
export const bookDetailSchema = z.object({
    "id": z.uuid(),
"name": z.string(),
"slug": z.nullable(z.string()),
"description": z.nullable(z.string()),
"isPublic": z.boolean(),
"isSystem": z.boolean(),
get "owner"(){
               return authorSchema.describe("Public author projection -- how a user is shown to *other* users.\n\nThe only user data exposed when homebrew is published (#185, consumed by\n#177+). Deliberately carries ``username`` alone: it is a unique,\nimmutable, stable public handle in Phase 1b, so neither the private\nemail nor the internal user id ever needs to leave the owner's own view.\nAdding fields later (e.g. a stable public id, should usernames ever\nbecome mutable) is an additive, non-breaking change.").nullable()
              },
"createdAt": z.iso.datetime(),
"updatedAt": z.iso.datetime(),
"monsterCount": z.int(),
"spellCount": z.int(),
"itemCount": z.int()
    }).describe("A single book with the count of content it holds, by resource type.")
