/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to update a book. Only the provided fields are changed.
 */
export const bookUpdateSchema = z.object({
    "name": z.string().min(1).max(255).nullish(),
"description": z.string().max(2000).nullish()
    }).describe("Payload to update a book. Only the provided fields are changed.")
