/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to create a book.
 */
export const bookCreateSchema = z.object({
    "name": z.string().min(1).max(255),
"description": z.string().max(2000).nullish()
    }).describe("Payload to create a book.")
