/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description A book owned by the requesting user that contains this content.
 */
export const bookMembershipSchema = z.object({
    "id": z.uuid().describe("Unique identifier for the book."),
"name": z.string().describe("Display name of the book."),
"slug": z.nullable(z.string().describe("Stable handle for system books; null for user books."))
    }).describe("A book owned by the requesting user that contains this content.")
