/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to invite a user to a campaign by their public handle.\n\nInvites go by handle, never email: the username is the public identity\n(#185), so this never discloses which private email addresses exist.
 */
export const campaignInviteCreateSchema = z.object({
    "handle": z.string().min(3).max(30).regex(/^[a-z0-9_-]+$/).describe("Public handle. Lowercase letters, digits, hyphen, and underscore only; 3-30 characters.")
    }).describe("Payload to invite a user to a campaign by their public handle.\n\nInvites go by handle, never email: the username is the public identity\n(#185), so this never discloses which private email addresses exist.")
