/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to create a campaign.
 */
export const campaignCreateSchema = z.object({
    "name": z.string().min(1).max(255).describe("Display name for the campaign."),
"description": z.string().max(2000).describe("Optional longer description of the campaign.").nullish()
    }).describe("Payload to create a campaign.")
