/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authorSchema } from "./authorSchema.ts";
import { z } from "zod/v4";

/**
 * @description A single campaign with its member and enabled-book counts.
 */
export const campaignDetailSchema = z.object({
    "id": z.uuid().describe("Unique identifier for the campaign."),
"name": z.string().describe("Display name of the campaign."),
"description": z.nullable(z.string().describe("Longer description, if any.")),
get "owner"(){
                return authorSchema.describe("Public author projection -- how a user is shown to *other* users.\n\nThe only user data exposed when homebrew is published (#185, consumed by\n#177+). Deliberately carries ``username`` alone: it is a unique,\nimmutable, stable public handle in Phase 1b, so neither the private\nemail nor the internal user id ever needs to leave the owner's own view.\nAdding fields later (e.g. a stable public id, should usernames ever\nbecome mutable) is an additive, non-breaking change.")
              },
"role": z.enum(["owner", "member"]).describe("The viewer's relationship to this campaign."),
"createdAt": z.iso.datetime().describe("When the campaign was created."),
"updatedAt": z.iso.datetime().describe("When the campaign was last updated."),
"memberCount": z.int().describe("Number of members, excluding the owner."),
"bookCount": z.int().describe("Number of books enabled on the campaign.")
    }).describe("A single campaign with its member and enabled-book counts.")
