/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to update a campaign. Only the provided fields are changed.
 */
export const campaignUpdateSchema = z.object({
    "name": z.string().min(1).max(255).describe("New display name for the campaign.").nullish(),
"description": z.string().max(2000).describe("New description for the campaign.").nullish()
    }).describe("Payload to update a campaign. Only the provided fields are changed.")
