/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authorSchema } from "./authorSchema.ts";
import { z } from "zod/v4";

/**
 * @description A member of a campaign, as shown in the roster.
 */
export const campaignMemberSummarySchema = z.object({
    get "user"(){
                return authorSchema.describe("Public author projection -- how a user is shown to *other* users.\n\nThe only user data exposed when homebrew is published (#185, consumed by\n#177+). Deliberately carries ``username`` alone: it is a unique,\nimmutable, stable public handle in Phase 1b, so neither the private\nemail nor the internal user id ever needs to leave the owner's own view.\nAdding fields later (e.g. a stable public id, should usernames ever\nbecome mutable) is an additive, non-breaking change.")
              },
"joinedAt": z.iso.datetime().describe("When the member joined (accepted their invite).")
    }).describe("A member of a campaign, as shown in the roster.")
