/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { changeEmailRequestSchema } from "./changeEmailRequestSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const changeEmailV1AccountEmailPut200Schema = z.lazy(() => userResponseSchema).describe("The owner's own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.")

/**
 * @description Not authenticated
 */
export const changeEmailV1AccountEmailPut401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description CSRF token or current password invalid
 */
export const changeEmailV1AccountEmailPut403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Email already registered or unchanged
 */
export const changeEmailV1AccountEmailPut409Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const changeEmailV1AccountEmailPut422Schema = z.lazy(() => HTTPValidationErrorSchema)

/**
 * @description Too many change-email requests
 */
export const changeEmailV1AccountEmailPut429Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const changeEmailV1AccountEmailPutMutationRequestSchema = z.lazy(() => changeEmailRequestSchema).describe("Payload to request an email change.\n\nThe new address is staged, not applied, until it is confirmed via the\nemailed link. The current password re-authenticates the request.")

export const changeEmailV1AccountEmailPutMutationResponseSchema = z.lazy(() => changeEmailV1AccountEmailPut200Schema)
