/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { changePasswordRequestSchema } from "./changePasswordRequestSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const changePasswordV1AccountPasswordPut204Schema = z.any()

/**
 * @description Not authenticated
 */
export const changePasswordV1AccountPasswordPut401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description CSRF token or current password invalid
 */
export const changePasswordV1AccountPasswordPut403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const changePasswordV1AccountPasswordPut422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const changePasswordV1AccountPasswordPutMutationRequestSchema = z.lazy(() => changePasswordRequestSchema).describe("Payload to change the signed-in user's password.\n\nThe current password re-authenticates the request, so a stolen session\nalone cannot rotate it. ``new_password`` follows the shared account\npassword rules.")

export const changePasswordV1AccountPasswordPutMutationResponseSchema = z.lazy(() => changePasswordV1AccountPasswordPut204Schema)
