/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to request an email change.\n\nThe new address is staged, not applied, until it is confirmed via the\nemailed link. The current password re-authenticates the request.
 */
export const changeEmailRequestSchema = z.object({
    "newEmail": z.email().describe("The address to move the account to (kept private)."),
"currentPassword": z.string().min(1).max(128).describe("The account's current password, for re-authentication.")
    }).describe("Payload to request an email change.\n\nThe new address is staged, not applied, until it is confirmed via the\nemailed link. The current password re-authenticates the request.")
