/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to change the signed-in user\'s password.\n\nThe current password re-authenticates the request, so a stolen session\nalone cannot rotate it. ``new_password`` follows the shared account\npassword rules.
 */
export const changePasswordRequestSchema = z.object({
    "currentPassword": z.string().min(1).max(128).describe("The account's current password, for re-authentication."),
"newPassword": z.string().min(8).max(128).describe("Account password (8-128 characters).")
    }).describe("Payload to change the signed-in user's password.\n\nThe current password re-authenticates the request, so a stolen session\nalone cannot rotate it. ``new_password`` follows the shared account\npassword rules.")
