/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { emailChangeConfirmRequestSchema } from "./emailChangeConfirmRequestSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const confirmEmailChangeV1AuthEmailChangeConfirmPost204Schema = z.any()

/**
 * @description Token is invalid or expired
 */
export const confirmEmailChangeV1AuthEmailChangeConfirmPost400Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Email already registered by another account
 */
export const confirmEmailChangeV1AuthEmailChangeConfirmPost409Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const confirmEmailChangeV1AuthEmailChangeConfirmPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const confirmEmailChangeV1AuthEmailChangeConfirmPostMutationRequestSchema = z.lazy(() => emailChangeConfirmRequestSchema).describe("Payload to confirm a pending email change with its token.")

export const confirmEmailChangeV1AuthEmailChangeConfirmPostMutationResponseSchema = z.lazy(() => confirmEmailChangeV1AuthEmailChangeConfirmPost204Schema)
