/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { passwordResetConfirmRequestSchema } from "./passwordResetConfirmRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const confirmPasswordResetV1AuthPasswordResetConfirmPost204Schema = z.any()

/**
 * @description Token is invalid or expired
 */
export const confirmPasswordResetV1AuthPasswordResetConfirmPost400Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const confirmPasswordResetV1AuthPasswordResetConfirmPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const confirmPasswordResetV1AuthPasswordResetConfirmPostMutationRequestSchema = z.lazy(() => passwordResetConfirmRequestSchema).describe("Payload to set a new password using a reset token.")

export const confirmPasswordResetV1AuthPasswordResetConfirmPostMutationResponseSchema = z.lazy(() => confirmPasswordResetV1AuthPasswordResetConfirmPost204Schema)
