/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description SRD content source attribution.\n\nAttributes:\n    type: Identifier for the kind of source (e.g. \"srd\").\n    license: Human-readable license name (e.g. \"CC BY 4.0\").\n    license_url: URL to the license text.\n    attribution: Required attribution string per the license.\n    data_provider: Origin of the seed data (e.g. \"5e-bits/5e-database\").\n    data_provider_url: URL to the data provider\'s source repo.
 */
export const contentSourceSchema = z.object({
    "type": z.string(),
"license": z.string(),
"licenseUrl": z.string(),
"attribution": z.string(),
"dataProvider": z.string(),
"dataProviderUrl": z.string()
    }).catchall(z.any()).describe("SRD content source attribution.\n\nAttributes:\n    type: Identifier for the kind of source (e.g. \"srd\").\n    license: Human-readable license name (e.g. \"CC BY 4.0\").\n    license_url: URL to the license text.\n    attribution: Required attribution string per the license.\n    data_provider: Origin of the seed data (e.g. \"5e-bits/5e-database\").\n    data_provider_url: URL to the data provider's source repo.")
