/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Item cost as a quantity + currency unit (gp, sp, cp, pp, ep).
 */
export const costSchema = z.object({
    "quantity": z.number(),
"unit": z.string()
    }).catchall(z.any()).describe("Item cost as a quantity + currency unit (gp, sp, cp, pp, ep).")
