/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { campaignCreateSchema } from "./campaignCreateSchema.ts";
import { campaignDetailSchema } from "./campaignDetailSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const createCampaignV1CampaignsPost201Schema = z.lazy(() => campaignDetailSchema).describe("A single campaign with its member and enabled-book counts.")

/**
 * @description Validation Error
 */
export const createCampaignV1CampaignsPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createCampaignV1CampaignsPostMutationRequestSchema = z.lazy(() => campaignCreateSchema).describe("Payload to create a campaign.")

export const createCampaignV1CampaignsPostMutationResponseSchema = z.lazy(() => createCampaignV1CampaignsPost201Schema)
