/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { bookCreateSchema } from "./bookCreateSchema.ts";
import { bookDetailSchema } from "./bookDetailSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const createBookV1BooksPost201Schema = z.lazy(() => bookDetailSchema).describe("A single book with the count of content it holds, by resource type.")

/**
 * @description Validation Error
 */
export const createBookV1BooksPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const createBookV1BooksPostMutationRequestSchema = z.lazy(() => bookCreateSchema).describe("Payload to create a book.")

export const createBookV1BooksPostMutationResponseSchema = z.lazy(() => createBookV1BooksPost201Schema)
