/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { srdReferenceSchema } from "./srdReferenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description Weapon damage roll (dice + optional flat bonus + damage type).
 */
export const damageSchema = z.object({
    "damageDice": z.string(),
"damageBonus": z.int().nullish(),
get "damageType"(){
                return srdReferenceSchema.describe("An SRD reference link.")
              }
    }).catchall(z.any()).describe("Weapon damage roll (dice + optional flat bonus + damage type).")
