/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const declineInviteV1CampaignInvitesInviteIdDeclinePostPathParamsSchema = z.object({
    "invite_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const declineInviteV1CampaignInvitesInviteIdDeclinePost204Schema = z.any()

/**
 * @description Invite not found, expired, or not addressed to you
 */
export const declineInviteV1CampaignInvitesInviteIdDeclinePost404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const declineInviteV1CampaignInvitesInviteIdDeclinePost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const declineInviteV1CampaignInvitesInviteIdDeclinePostMutationResponseSchema = z.lazy(() => declineInviteV1CampaignInvitesInviteIdDeclinePost204Schema)
