/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const deleteBookV1BooksBookIdDeletePathParamsSchema = z.object({
    "book_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const deleteBookV1BooksBookIdDelete204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const deleteBookV1BooksBookIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book not found
 */
export const deleteBookV1BooksBookIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const deleteBookV1BooksBookIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const deleteBookV1BooksBookIdDeleteMutationResponseSchema = z.lazy(() => deleteBookV1BooksBookIdDelete204Schema)
