/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const deleteCampaignV1CampaignsCampaignIdDeletePathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const deleteCampaignV1CampaignsCampaignIdDelete204Schema = z.any()

/**
 * @description Not the campaign\'s owner
 */
export const deleteCampaignV1CampaignsCampaignIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const deleteCampaignV1CampaignsCampaignIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const deleteCampaignV1CampaignsCampaignIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const deleteCampaignV1CampaignsCampaignIdDeleteMutationResponseSchema = z.lazy(() => deleteCampaignV1CampaignsCampaignIdDelete204Schema)
