/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { accountDeleteRequestSchema } from "./accountDeleteRequestSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const deleteAccountV1AccountDelete204Schema = z.any()

/**
 * @description Not authenticated
 */
export const deleteAccountV1AccountDelete401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description CSRF token or re-auth password invalid
 */
export const deleteAccountV1AccountDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const deleteAccountV1AccountDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const deleteAccountV1AccountDeleteMutationRequestSchema = z.lazy(() => accountDeleteRequestSchema).describe("Payload to delete the current account.\n\nThe current password is required as a re-authentication step, so a\nstolen session alone cannot destroy the account. Deletion is\nirreversible.")

export const deleteAccountV1AccountDeleteMutationResponseSchema = z.lazy(() => deleteAccountV1AccountDelete204Schema)
