/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const disableBookV1CampaignsCampaignIdBooksBookIdDeletePathParamsSchema = z.object({
    "campaign_id": z.uuid(),
"book_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const disableBookV1CampaignsCampaignIdBooksBookIdDelete204Schema = z.any()

/**
 * @description Not the campaign\'s owner
 */
export const disableBookV1CampaignsCampaignIdBooksBookIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const disableBookV1CampaignsCampaignIdBooksBookIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const disableBookV1CampaignsCampaignIdBooksBookIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const disableBookV1CampaignsCampaignIdBooksBookIdDeleteMutationResponseSchema = z.lazy(() => disableBookV1CampaignsCampaignIdBooksBookIdDelete204Schema)
