/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to confirm a pending email change with its token.
 */
export const emailChangeConfirmRequestSchema = z.object({
    "token": z.string().min(1).describe("Email-change token from the confirmation link.")
    }).describe("Payload to confirm a pending email change with its token.")
