/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const enableBookV1CampaignsCampaignIdBooksBookIdPutPathParamsSchema = z.object({
    "campaign_id": z.uuid(),
"book_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const enableBookV1CampaignsCampaignIdBooksBookIdPut204Schema = z.any()

/**
 * @description Not the campaign\'s owner
 */
export const enableBookV1CampaignsCampaignIdBooksBookIdPut403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const enableBookV1CampaignsCampaignIdBooksBookIdPut404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const enableBookV1CampaignsCampaignIdBooksBookIdPut422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const enableBookV1CampaignsCampaignIdBooksBookIdPutMutationResponseSchema = z.lazy(() => enableBookV1CampaignsCampaignIdBooksBookIdPut204Schema)
