/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Standard error response schema.
 */
export const errorResponseSchema = z.object({
    "status": z.int(),
"developerMessage": z.string(),
"userMessage": z.string(),
"errorCode": z.string(),
"moreInfo": z.string()
    }).describe("Standard error response schema.")
