/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { accountExportSchema } from "./accountExportSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const exportAccountV1AccountExportGet200Schema = z.lazy(() => accountExportSchema).describe("A portable copy of everything stored for the current account.")

/**
 * @description Not authenticated
 */
export const exportAccountV1AccountExportGet401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const exportAccountV1AccountExportGetQueryResponseSchema = z.lazy(() => exportAccountV1AccountExportGet200Schema)
