/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { bookDetailSchema } from "./bookDetailSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const getBookV1BooksBookIdGetPathParamsSchema = z.object({
    "book_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const getBookV1BooksBookIdGet200Schema = z.lazy(() => bookDetailSchema).describe("A single book with the count of content it holds, by resource type.")

/**
 * @description Book not found
 */
export const getBookV1BooksBookIdGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const getBookV1BooksBookIdGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getBookV1BooksBookIdGetQueryResponseSchema = z.lazy(() => getBookV1BooksBookIdGet200Schema)
