/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { campaignDetailSchema } from "./campaignDetailSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const getCampaignV1CampaignsCampaignIdGetPathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const getCampaignV1CampaignsCampaignIdGet200Schema = z.lazy(() => campaignDetailSchema).describe("A single campaign with its member and enabled-book counts.")

/**
 * @description Campaign not found
 */
export const getCampaignV1CampaignsCampaignIdGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const getCampaignV1CampaignsCampaignIdGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getCampaignV1CampaignsCampaignIdGetQueryResponseSchema = z.lazy(() => getCampaignV1CampaignsCampaignIdGet200Schema)
