/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { itemDetailSchema } from "./itemDetailSchema.ts";
import { z } from "zod/v4";

export const getItemV1ItemsSlugGetPathParamsSchema = z.object({
    "slug": z.string()
    })

export const getItemV1ItemsSlugGetQueryParamsSchema = z.object({
    "namespace": z.string().default("srd-5.1").describe("The source namespace of the item, used to disambiguate items with the same slug from different sources. Known values: 'srd-5.1', 'srd-2024', 'user:{user_id}'."),
"include": z.string().describe("Comma-separated optional response expansions. Supported: 'book_memberships' annotates each entry with the signed-in user's own books that contain it.").nullish()
    })

/**
 * @description Successful Response
 */
export const getItemV1ItemsSlugGet200Schema = z.lazy(() => itemDetailSchema).describe("Full item details, used in detail endpoints.")

/**
 * @description Item not found
 */
export const getItemV1ItemsSlugGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const getItemV1ItemsSlugGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getItemV1ItemsSlugGetQueryResponseSchema = z.lazy(() => getItemV1ItemsSlugGet200Schema)
