/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { monsterDetailSchema } from "./monsterDetailSchema.ts";
import { z } from "zod/v4";

export const getMonsterV1MonstersSlugGetPathParamsSchema = z.object({
    "slug": z.string()
    })

export const getMonsterV1MonstersSlugGetQueryParamsSchema = z.object({
    "namespace": z.string().default("srd-5.1").describe("Source namespace to search in. Defaults to the SRD 5.1 namespace. Use 'user:{user_id}' for homebrew content."),
"include": z.string().describe("Comma-separated optional response expansions. Supported: 'book_memberships' annotates each entry with the signed-in user's own books that contain it.").nullish()
    })

/**
 * @description Successful Response
 */
export const getMonsterV1MonstersSlugGet200Schema = z.lazy(() => monsterDetailSchema).describe("Full monster details, used in detail endpoints.")

/**
 * @description Monster not found
 */
export const getMonsterV1MonstersSlugGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const getMonsterV1MonstersSlugGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getMonsterV1MonstersSlugGetQueryResponseSchema = z.lazy(() => getMonsterV1MonstersSlugGet200Schema)
