/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { monsterDetailSchema } from "./monsterDetailSchema.ts";
import { z } from "zod/v4";

export const getMonsterV1MonstersSlugGetPathParamsSchema = z.object({
    "slug": z.string()
    })

export const getMonsterV1MonstersSlugGetQueryParamsSchema = z.object({
    "namespace": z.string().default("srd-5.1").describe("Source namespace to search in. Defaults to the SRD 5.1 namespace. Use 'user:{user_id}' for homebrew content.")
    })

/**
 * @description Successful Response
 */
export const getMonsterV1MonstersSlugGet200Schema = z.lazy(() => monsterDetailSchema).describe("Full monster details, used in detail endpoints.\n\nAttributes:\n    content: The full monster data as ingested from the source, with all\n        original fields and structure preserved.\n    content_source: Metadata about the source of the monster data, such as\n        the original URL or source file name.")

/**
 * @description Monster not found
 */
export const getMonsterV1MonstersSlugGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const getMonsterV1MonstersSlugGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getMonsterV1MonstersSlugGetQueryResponseSchema = z.lazy(() => getMonsterV1MonstersSlugGet200Schema)
