/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { spellDetailSchema } from "./spellDetailSchema.ts";
import { z } from "zod/v4";

export const getSpellV1SpellsSlugGetPathParamsSchema = z.object({
    "slug": z.string()
    })

export const getSpellV1SpellsSlugGetQueryParamsSchema = z.object({
    "namespace": z.string().default("srd-5.1").describe("Source namespace to search in. Defaults to the SRD 5.1 namespace. Use 'user:{user_id}' for homebrew content."),
"include": z.string().describe("Comma-separated optional response expansions. Supported: 'book_memberships' annotates each entry with the signed-in user's own books that contain it.").nullish()
    })

/**
 * @description Successful Response
 */
export const getSpellV1SpellsSlugGet200Schema = z.lazy(() => spellDetailSchema).describe("Full spell details, used in the detail endpoint.")

/**
 * @description Spell not found
 */
export const getSpellV1SpellsSlugGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const getSpellV1SpellsSlugGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const getSpellV1SpellsSlugGetQueryResponseSchema = z.lazy(() => getSpellV1SpellsSlugGet200Schema)
