/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Response schema for the health check endpoint.
 */
export const healthResponseSchema = z.object({
    "status": z.string(),
"version": z.string()
    }).describe("Response schema for the health check endpoint.")
