/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { healthResponseSchema } from "./healthResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const healthCheckHealthGet200Schema = z.lazy(() => healthResponseSchema).describe("Response schema for the health check endpoint.")

export const healthCheckHealthGetQueryResponseSchema = z.lazy(() => healthCheckHealthGet200Schema)
