/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { campaignInviteCreateSchema } from "./campaignInviteCreateSchema.ts";
import { campaignInviteSummarySchema } from "./campaignInviteSummarySchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const inviteMemberV1CampaignsCampaignIdInvitesPostPathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost201Schema = z.lazy(() => campaignInviteSummarySchema).describe("A pending invite, as the campaign owner sees it.\n\nCarries the invitee's public handle only -- never their email or id.")

/**
 * @description Cannot invite yourself
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost400Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Not the campaign\'s owner
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign or user not found
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description That user is already a member or already invited
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost409Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

/**
 * @description Too many invites
 */
export const inviteMemberV1CampaignsCampaignIdInvitesPost429Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const inviteMemberV1CampaignsCampaignIdInvitesPostMutationRequestSchema = z.lazy(() => campaignInviteCreateSchema).describe("Payload to invite a user to a campaign by their public handle.\n\nInvites go by handle, never email: the username is the public identity\n(#185), so this never discloses which private email addresses exist.")

export const inviteMemberV1CampaignsCampaignIdInvitesPostMutationResponseSchema = z.lazy(() => inviteMemberV1CampaignsCampaignIdInvitesPost201Schema)
