/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Summary info for an item, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the item, used in URLs.\n    name: The item\'s name.\n    item_category: The category of the item (e.g. \"Weapon\", \"Potion\"),\n        if available. This is not guaranteed to be present for all items, as\n        it depends on the source data.\n    rarity: The rarity of the item (e.g. \"Common\", \"Rare\"), if available.
 */
export const itemSummarySchema = z.object({
    "slug": z.string(),
"name": z.string(),
"itemCategory": z.nullable(z.string()),
"rarity": z.nullable(z.string())
    }).describe("Summary info for an item, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the item, used in URLs.\n    name: The item's name.\n    item_category: The category of the item (e.g. \"Weapon\", \"Potion\"),\n        if available. This is not guaranteed to be present for all items, as\n        it depends on the source data.\n    rarity: The rarity of the item (e.g. \"Common\", \"Rare\"), if available.")
