/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { contentSourceSchema } from "./contentSourceSchema.ts";
import { srdItemContentSchema } from "./srdItemContentSchema.ts";
import { z } from "zod/v4";

/**
 * @description Full item details, used in detail endpoints.
 */
export const itemDetailSchema = z.object({
    "slug": z.string().describe("URL-safe unique identifier."),
"name": z.string().describe("The item's name."),
"itemCategory": z.nullable(z.string().describe("Category (e.g. 'weapon', 'potion'), if available.")),
"rarity": z.nullable(z.string().describe("Rarity (e.g. 'rare'); null for mundane items.")),
get "content"(){
                return srdItemContentSchema.describe("SRD item content payload.")
              },
get "contentSource"(){
                return contentSourceSchema.describe("SRD content source attribution.\n\nAttributes:\n    type: Identifier for the kind of source (e.g. \"srd\").\n    license: Human-readable license name (e.g. \"CC BY 4.0\").\n    license_url: URL to the license text.\n    attribution: Required attribution string per the license.\n    data_provider: Origin of the seed data (e.g. \"5e-bits/5e-database\").\n    data_provider_url: URL to the data provider's source repo.")
              }
    }).describe("Full item details, used in detail endpoints.")
