/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Full item details, used in detail endpoints.\n\nAttributes:\n    content: The full item data as ingested from the source, with all\n        original fields and structure preserved.\n    content_source: Metadata about the source of the item data, such as\n        the original URL or source file name.
 */
export const itemDetailSchema = z.object({
    "slug": z.string(),
"name": z.string(),
"itemCategory": z.nullable(z.string()),
"rarity": z.nullable(z.string()),
"content": z.object({

    }).catchall(z.any()),
"contentSource": z.object({

    }).catchall(z.any())
    }).describe("Full item details, used in detail endpoints.\n\nAttributes:\n    content: The full item data as ingested from the source, with all\n        original fields and structure preserved.\n    content_source: Metadata about the source of the item data, such as\n        the original URL or source file name.")
