/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Summary info for an item, used in list endpoints.
 */
export const itemSummarySchema = z.object({
    "slug": z.string().describe("URL-safe unique identifier."),
"name": z.string().describe("The item's name."),
"itemCategory": z.nullable(z.string().describe("Category (e.g. 'weapon', 'potion'), if available.")),
"rarity": z.nullable(z.string().describe("Rarity (e.g. 'rare'); null for mundane items."))
    }).describe("Summary info for an item, used in list endpoints.")
