/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Prev/next navigation links for a paginated resultset.\n\nAttributes:\n    prev: Absolute URL for the previous page, or null on the first page.\n    next: Absolute URL for the next page, or null on the last page.
 */
export const linksSchema = z.object({
    "prev": z.nullable(z.string()),
"next": z.nullable(z.string())
    }).describe("Prev/next navigation links for a paginated resultset.\n\nAttributes:\n    prev: Absolute URL for the previous page, or null on the first page.\n    next: Absolute URL for the next page, or null on the last page.")
