/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Prev/next navigation links for a paginated resultset.
 */
export const linksSchema = z.object({
    "prev": z.nullable(z.string().describe("URL of the previous page, or null on the first page.")),
"next": z.nullable(z.string().describe("URL of the next page, or null on the last page."))
    }).describe("Prev/next navigation links for a paginated resultset.")
