/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { paginatedResultsetMonsterSummarySchema } from "./paginatedResultsetMonsterSummarySchema.ts";
import { z } from "zod/v4";

export const listBookMonstersV1BooksBookIdMonstersGetPathParamsSchema = z.object({
    "book_id": z.uuid()
    })

export const listBookMonstersV1BooksBookIdMonstersGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: challenge_rating, monster_type, name.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name, monster_type. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listBookMonstersV1BooksBookIdMonstersGet200Schema = z.lazy(() => paginatedResultsetMonsterSummarySchema)

/**
 * @description Book or content not found
 */
export const listBookMonstersV1BooksBookIdMonstersGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const listBookMonstersV1BooksBookIdMonstersGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listBookMonstersV1BooksBookIdMonstersGetQueryResponseSchema = z.lazy(() => listBookMonstersV1BooksBookIdMonstersGet200Schema)
