/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { myCampaignInviteSchema } from "./myCampaignInviteSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const listMyInvitesV1CampaignInvitesGet200Schema = z.array(z.lazy(() => myCampaignInviteSchema).describe("A pending invite addressed to the current user.\n\nShows the campaign and its owner's public handle so the invitee knows who\ninvited them and to what; no data about other members is exposed."))

export const listMyInvitesV1CampaignInvitesGetQueryResponseSchema = z.lazy(() => listMyInvitesV1CampaignInvitesGet200Schema)
