/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { campaignInviteSummarySchema } from "./campaignInviteSummarySchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const listInvitesV1CampaignsCampaignIdInvitesGetPathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const listInvitesV1CampaignsCampaignIdInvitesGet200Schema = z.array(z.lazy(() => campaignInviteSummarySchema).describe("A pending invite, as the campaign owner sees it.\n\nCarries the invitee's public handle only -- never their email or id."))

/**
 * @description Not the campaign\'s owner
 */
export const listInvitesV1CampaignsCampaignIdInvitesGet403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const listInvitesV1CampaignsCampaignIdInvitesGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const listInvitesV1CampaignsCampaignIdInvitesGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listInvitesV1CampaignsCampaignIdInvitesGetQueryResponseSchema = z.lazy(() => listInvitesV1CampaignsCampaignIdInvitesGet200Schema)
