/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { paginatedResultsetSpellSummarySchema } from "./paginatedResultsetSpellSummarySchema.ts";
import { z } from "zod/v4";

export const listBookSpellsV1BooksBookIdSpellsGetPathParamsSchema = z.object({
    "book_id": z.uuid()
    })

export const listBookSpellsV1BooksBookIdSpellsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: level, name, school.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listBookSpellsV1BooksBookIdSpellsGet200Schema = z.lazy(() => paginatedResultsetSpellSummarySchema)

/**
 * @description Book or content not found
 */
export const listBookSpellsV1BooksBookIdSpellsGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const listBookSpellsV1BooksBookIdSpellsGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listBookSpellsV1BooksBookIdSpellsGetQueryResponseSchema = z.lazy(() => listBookSpellsV1BooksBookIdSpellsGet200Schema)
