/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorResponseSchema } from "./errorResponseSchema.ts";
import { paginatedResultsetMonsterSummarySchema } from "./paginatedResultsetMonsterSummarySchema.ts";
import { z } from "zod/v4";

export const listMonstersV1MonstersGetQueryParamsSchema = z.object({
    "type": z.string().describe("Exact match on monster type (e.g. 'undead').").nullish(),
"cr_min": z.union([z.coerce.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)]).describe("Inclusive minimum challenge rating.").nullish(),
"cr_max": z.union([z.coerce.number(), z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)]).describe("Inclusive maximum challenge rating.").nullish(),
"limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: challenge_rating, monster_type, name.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name, monster_type. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listMonstersV1MonstersGet200Schema = z.lazy(() => paginatedResultsetMonsterSummarySchema)

/**
 * @description Validation error
 */
export const listMonstersV1MonstersGet422Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const listMonstersV1MonstersGetQueryResponseSchema = z.lazy(() => listMonstersV1MonstersGet200Schema)
