/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { campaignMemberSummarySchema } from "./campaignMemberSummarySchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const listMembersV1CampaignsCampaignIdMembersGetPathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const listMembersV1CampaignsCampaignIdMembersGet200Schema = z.array(z.lazy(() => campaignMemberSummarySchema).describe("A member of a campaign, as shown in the roster."))

/**
 * @description Campaign not found
 */
export const listMembersV1CampaignsCampaignIdMembersGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const listMembersV1CampaignsCampaignIdMembersGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listMembersV1CampaignsCampaignIdMembersGetQueryResponseSchema = z.lazy(() => listMembersV1CampaignsCampaignIdMembersGet200Schema)
