/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { paginatedResultsetCampaignSummarySchema } from "./paginatedResultsetCampaignSummarySchema.ts";
import { z } from "zod/v4";

export const listCampaignsV1CampaignsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: created_at, name, updated_at.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name, description. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listCampaignsV1CampaignsGet200Schema = z.lazy(() => paginatedResultsetCampaignSummarySchema)

/**
 * @description Validation Error
 */
export const listCampaignsV1CampaignsGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listCampaignsV1CampaignsGetQueryResponseSchema = z.lazy(() => listCampaignsV1CampaignsGet200Schema)
