/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { paginatedResultsetBookSummarySchema } from "./paginatedResultsetBookSummarySchema.ts";
import { z } from "zod/v4";

export const listBooksV1BooksGetQueryParamsSchema = z.object({
    "scope": z.enum(["all", "owned"]).default("all").describe("Which books to include: 'all' (your books plus public books) or 'owned' (only books you created)."),
"limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: created_at, name, updated_at.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name, description. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listBooksV1BooksGet200Schema = z.lazy(() => paginatedResultsetBookSummarySchema)

/**
 * @description Validation Error
 */
export const listBooksV1BooksGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listBooksV1BooksGetQueryResponseSchema = z.lazy(() => listBooksV1BooksGet200Schema)
