/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { paginatedResultsetBookSummarySchema } from "./paginatedResultsetBookSummarySchema.ts";
import { z } from "zod/v4";

export const listCampaignBooksV1CampaignsCampaignIdBooksGetPathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

export const listCampaignBooksV1CampaignsCampaignIdBooksGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: name.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name, description. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listCampaignBooksV1CampaignsCampaignIdBooksGet200Schema = z.lazy(() => paginatedResultsetBookSummarySchema)

/**
 * @description Campaign not found
 */
export const listCampaignBooksV1CampaignsCampaignIdBooksGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const listCampaignBooksV1CampaignsCampaignIdBooksGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listCampaignBooksV1CampaignsCampaignIdBooksGetQueryResponseSchema = z.lazy(() => listCampaignBooksV1CampaignsCampaignIdBooksGet200Schema)
