/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorResponseSchema } from "./errorResponseSchema.ts";
import { paginatedResultsetSpellSummarySchema } from "./paginatedResultsetSpellSummarySchema.ts";
import { z } from "zod/v4";

export const listSpellsV1SpellsGetQueryParamsSchema = z.object({
    "school": z.string().describe("Exact match on spell school (e.g. 'evocation').").nullish(),
"level_min": z.coerce.number().int().min(0).max(9).describe("Inclusive minimum spell level (0-9).").nullish(),
"level_max": z.coerce.number().int().min(0).max(9).describe("Inclusive maximum spell level (0-9).").nullish(),
"limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: level, name, school.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listSpellsV1SpellsGet200Schema = z.lazy(() => paginatedResultsetSpellSummarySchema)

/**
 * @description Validation error
 */
export const listSpellsV1SpellsGet422Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const listSpellsV1SpellsGetQueryResponseSchema = z.lazy(() => listSpellsV1SpellsGet200Schema)
