/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { paginatedResultsetItemSummarySchema } from "./paginatedResultsetItemSummarySchema.ts";
import { z } from "zod/v4";

export const listBookItemsV1BooksBookIdItemsGetPathParamsSchema = z.object({
    "book_id": z.uuid()
    })

export const listBookItemsV1BooksBookIdItemsGetQueryParamsSchema = z.object({
    "limit": z.coerce.number().int().min(1).max(100).default(20),
"offset": z.coerce.number().int().min(0).default(0),
"order_by": z.string().describe("Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: item_category, name, rarity.").nullish(),
"search": z.string().describe("Case-insensitive substring search. Matches against name, item_category. Results are relevance-ordered: earlier columns rank higher than later ones.").nullish()
    })

/**
 * @description Successful Response
 */
export const listBookItemsV1BooksBookIdItemsGet200Schema = z.lazy(() => paginatedResultsetItemSummarySchema)

/**
 * @description Book or content not found
 */
export const listBookItemsV1BooksBookIdItemsGet404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const listBookItemsV1BooksBookIdItemsGet422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const listBookItemsV1BooksBookIdItemsGetQueryResponseSchema = z.lazy(() => listBookItemsV1BooksBookIdItemsGet200Schema)
