/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { loginRequestSchema } from "./loginRequestSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const loginV1AuthLoginPost200Schema = z.lazy(() => userResponseSchema).describe("Public representation of a user; never includes the password hash.")

/**
 * @description Invalid credentials
 */
export const loginV1AuthLoginPost401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const loginV1AuthLoginPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const loginV1AuthLoginPostMutationRequestSchema = z.lazy(() => loginRequestSchema).describe("Payload to authenticate with email and password.")

export const loginV1AuthLoginPostMutationResponseSchema = z.lazy(() => loginV1AuthLoginPost200Schema)
