/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { loginRequestSchema } from "./loginRequestSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const loginV1AuthLoginPost200Schema = z.lazy(() => userResponseSchema).describe("The owner's own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.")

/**
 * @description Invalid credentials
 */
export const loginV1AuthLoginPost401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const loginV1AuthLoginPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

/**
 * @description Too many login attempts
 */
export const loginV1AuthLoginPost429Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const loginV1AuthLoginPostMutationRequestSchema = z.lazy(() => loginRequestSchema).describe("Payload to authenticate with a username-or-email and password.\n\n``identifier`` accepts either the account's username or its email; the\npresence of ``@`` disambiguates (usernames cannot contain ``@``).")

export const loginV1AuthLoginPostMutationResponseSchema = z.lazy(() => loginV1AuthLoginPost200Schema)
