/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to authenticate with email and password.
 */
export const loginRequestSchema = z.object({
    "email": z.email(),
"password": z.string().min(1).max(128)
    }).describe("Payload to authenticate with email and password.")
