/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { z } from "zod/v4";

export const logoutV1AuthLogoutPostQueryParamsSchema = z.object({
    "everywhere": z.boolean().default(false).describe("Revoke all of this user's sessions, not just this.")
    })

/**
 * @description Successful Response
 */
export const logoutV1AuthLogoutPost204Schema = z.any()

/**
 * @description Validation Error
 */
export const logoutV1AuthLogoutPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const logoutV1AuthLogoutPostMutationResponseSchema = z.lazy(() => logoutV1AuthLogoutPost204Schema)
