/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description A generic, non-revealing acknowledgement message.
 */
export const messageResponseSchema = z.object({
    "message": z.string()
    }).describe("A generic, non-revealing acknowledgement message.")
