/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { linksSchema } from "./linksSchema.ts";
import { resultsetMetaSchema } from "./resultsetMetaSchema.ts";
import { z } from "zod/v4";

/**
 * @description Envelopes a paginated resultset with metadata.
 */
export const metadataEnvelopeSchema = z.object({
    get "resultset"(){
                return resultsetMetaSchema.describe("Metadata about a paginated resultset.")
              },
get "links"(){
                return linksSchema.describe("Prev/next navigation links for a paginated resultset.")
              }
    }).describe("Envelopes a paginated resultset with metadata.")
