/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorResponseSchema } from "./errorResponseSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const meV1AuthMeGet200Schema = z.lazy(() => userResponseSchema).describe("Public representation of a user; never includes the password hash.")

/**
 * @description Not authenticated
 */
export const meV1AuthMeGet401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const meV1AuthMeGetQueryResponseSchema = z.lazy(() => meV1AuthMeGet200Schema)
