/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorResponseSchema } from "./errorResponseSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const meV1AuthMeGet200Schema = z.lazy(() => userResponseSchema).describe("The owner's own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.")

/**
 * @description Not authenticated
 */
export const meV1AuthMeGet401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const meV1AuthMeGetQueryResponseSchema = z.lazy(() => meV1AuthMeGet200Schema)
