/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Full monster details, used in detail endpoints.\n\nAttributes:\n    content: The full monster data as ingested from the source, with all\n        original fields and structure preserved.\n    content_source: Metadata about the source of the monster data, such as\n        the original URL or source file name.
 */
export const monsterDetailSchema = z.object({
    "slug": z.string(),
"name": z.string(),
"monsterType": z.nullable(z.string()),
"challengeRating": z.string(),
"content": z.object({

    }).catchall(z.any()),
"contentSource": z.object({

    }).catchall(z.any())
    }).describe("Full monster details, used in detail endpoints.\n\nAttributes:\n    content: The full monster data as ingested from the source, with all\n        original fields and structure preserved.\n    content_source: Metadata about the source of the monster data, such as\n        the original URL or source file name.")
