/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Summary info for a monster, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the monster, used in URLs.\n    name: The monster\'s name.\n    monster_type: The type or category of the monster (e.g. \"Dragon\").\n    challenge_rating: The monster\'s challenge rating as a display string\n        (e.g. \"1/2\", \"5\", \"10\").
 */
export const monsterSummarySchema = z.object({
    "slug": z.string(),
"name": z.string(),
"monsterType": z.nullable(z.string()),
"challengeRating": z.string()
    }).describe("Summary info for a monster, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the monster, used in URLs.\n    name: The monster's name.\n    monster_type: The type or category of the monster (e.g. \"Dragon\").\n    challenge_rating: The monster's challenge rating as a display string\n        (e.g. \"1/2\", \"5\", \"10\").")
