/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Summary info for a monster, used in list endpoints.
 */
export const monsterSummarySchema = z.object({
    "slug": z.string().describe("URL-safe unique identifier."),
"name": z.string().describe("The monster's name."),
"monsterType": z.nullable(z.string().describe("Type or category (e.g. 'dragon').")),
"challengeRating": z.string().describe("Challenge rating as a display string (e.g. '1/2', '5').")
    }).describe("Summary info for a monster, used in list endpoints.")
