/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authorSchema } from "./authorSchema.ts";
import { z } from "zod/v4";

/**
 * @description A pending invite addressed to the current user.\n\nShows the campaign and its owner\'s public handle so the invitee knows who\ninvited them and to what; no data about other members is exposed.
 */
export const myCampaignInviteSchema = z.object({
    "id": z.uuid().describe("Unique identifier for the invite."),
"campaignId": z.uuid().describe("The campaign the invite is for."),
"campaignName": z.string().describe("Name of the campaign."),
get "owner"(){
                return authorSchema.describe("Public author projection -- how a user is shown to *other* users.\n\nThe only user data exposed when homebrew is published (#185, consumed by\n#177+). Deliberately carries ``username`` alone: it is a unique,\nimmutable, stable public handle in Phase 1b, so neither the private\nemail nor the internal user id ever needs to leave the owner's own view.\nAdding fields later (e.g. a stable public id, should usernames ever\nbecome mutable) is an additive, non-breaking change.")
              },
"expiresAt": z.iso.datetime().describe("When the invite lapses if not accepted."),
"createdAt": z.iso.datetime().describe("When the invite was created.")
    }).describe("A pending invite addressed to the current user.\n\nShows the campaign and its owner's public handle so the invitee knows who\ninvited them and to what; no data about other members is exposed.")
