/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { metadataEnvelopeSchema } from "./metadataEnvelopeSchema.ts";
import { monsterSummarySchema } from "./monsterSummarySchema.ts";
import { z } from "zod/v4";

export const paginatedResultsetMonsterSummarySchema = z.object({
    get "metadata"(){
                return metadataEnvelopeSchema.describe("Envelopes a paginated resultset with metadata.")
              },
get "data"(){
                return z.array(monsterSummarySchema.describe("Summary info for a monster, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the monster, used in URLs.\n    name: The monster's name.\n    monster_type: The type or category of the monster (e.g. \"Dragon\").\n    challenge_rating: The monster's challenge rating as a display string\n        (e.g. \"1/2\", \"5\", \"10\")."))
              }
    })
