/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { bookSummarySchema } from "./bookSummarySchema.ts";
import { metadataEnvelopeSchema } from "./metadataEnvelopeSchema.ts";
import { z } from "zod/v4";

export const paginatedResultsetBookSummarySchema = z.object({
    get "metadata"(){
                return metadataEnvelopeSchema.describe("Envelopes a paginated resultset with metadata.")
              },
get "data"(){
                return z.array(bookSummarySchema.describe("A book as shown in list views.")).describe("The records on this page.")
              }
    })
