/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { metadataEnvelopeSchema } from "./metadataEnvelopeSchema.ts";
import { monsterSummarySchema } from "./monsterSummarySchema.ts";
import { z } from "zod/v4";

export const paginatedResultsetMonsterSummarySchema = z.object({
    get "metadata"(){
                return metadataEnvelopeSchema.describe("Envelopes a paginated resultset with metadata.")
              },
get "data"(){
                return z.array(monsterSummarySchema.describe("Summary info for a monster, used in list endpoints.")).describe("The records on this page.")
              }
    })
