/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { bookSummarySchema } from "./bookSummarySchema.ts";
import { metadataEnvelopeSchema } from "./metadataEnvelopeSchema.ts";
import { z } from "zod/v4";

export const paginatedResultsetBookSummarySchema = z.object({
    get "metadata"(){
                return metadataEnvelopeSchema.describe("Envelopes a paginated resultset with metadata.")
              },
get "data"(){
                return z.array(bookSummarySchema.describe("A book as shown in list views.\n\n``owner`` is the public author projection (username only) for a\nuser-owned book, or null for a system book such as the SRD catalog.\n``isSystem`` books are read-only; ``isPublic`` books are readable by\nanyone."))
              }
    })
