/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { campaignSummarySchema } from "./campaignSummarySchema.ts";
import { metadataEnvelopeSchema } from "./metadataEnvelopeSchema.ts";
import { z } from "zod/v4";

export const paginatedResultsetCampaignSummarySchema = z.object({
    get "metadata"(){
                return metadataEnvelopeSchema.describe("Envelopes a paginated resultset with metadata.")
              },
get "data"(){
                return z.array(campaignSummarySchema.describe("A campaign as shown in list views.")).describe("The records on this page.")
              }
    })
