/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { itemSummarySchema } from "./itemSummarySchema.ts";
import { metadataEnvelopeSchema } from "./metadataEnvelopeSchema.ts";
import { z } from "zod/v4";

export const paginatedResultsetItemSummarySchema = z.object({
    get "metadata"(){
                return metadataEnvelopeSchema.describe("Envelopes a paginated resultset with metadata.")
              },
get "data"(){
                return z.array(itemSummarySchema.describe("Summary info for an item, used in list endpoints.")).describe("The records on this page.")
              }
    })
