/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to request a password-reset email.\n\n``identifier`` is the account\'s username or email (same matching as\nlogin). The response is identical whether or not an account matches, so\nit never reveals which addresses are registered.
 */
export const passwordResetRequestSchema = z.object({
    "identifier": z.string().min(1).max(255)
    }).describe("Payload to request a password-reset email.\n\n``identifier`` is the account's username or email (same matching as\nlogin). The response is identical whether or not an account matches, so\nit never reveals which addresses are registered.")
