/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { srdReferenceSchema } from "./srdReferenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description A saving-throw or skill proficiency; index on `proficiency.index`.
 */
export const proficiencySchema = z.object({
    "value": z.int(),
get "proficiency"(){
                return srdReferenceSchema.describe("An SRD reference link.")
              }
    }).catchall(z.any()).describe("A saving-throw or skill proficiency; index on `proficiency.index`.")
