/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Weapon range in feet. `long` is omitted on melee weapons.
 */
export const rangeSchema = z.object({
    "normal": z.number(),
"long": z.number().nullish()
    }).catchall(z.any()).describe("Weapon range in feet. `long` is omitted on melee weapons.")
