/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const removeBookItemV1BooksBookIdItemsItemIdDeletePathParamsSchema = z.object({
    "book_id": z.uuid(),
"item_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const removeBookItemV1BooksBookIdItemsItemIdDelete204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const removeBookItemV1BooksBookIdItemsItemIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book or content not found
 */
export const removeBookItemV1BooksBookIdItemsItemIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const removeBookItemV1BooksBookIdItemsItemIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const removeBookItemV1BooksBookIdItemsItemIdDeleteMutationResponseSchema = z.lazy(() => removeBookItemV1BooksBookIdItemsItemIdDelete204Schema)
