/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const removeBookSpellV1BooksBookIdSpellsSpellIdDeletePathParamsSchema = z.object({
    "book_id": z.uuid(),
"spell_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const removeBookSpellV1BooksBookIdSpellsSpellIdDelete204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const removeBookSpellV1BooksBookIdSpellsSpellIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book or content not found
 */
export const removeBookSpellV1BooksBookIdSpellsSpellIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const removeBookSpellV1BooksBookIdSpellsSpellIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const removeBookSpellV1BooksBookIdSpellsSpellIdDeleteMutationResponseSchema = z.lazy(() => removeBookSpellV1BooksBookIdSpellsSpellIdDelete204Schema)
