/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const removeMemberV1CampaignsCampaignIdMembersHandleDeletePathParamsSchema = z.object({
    "campaign_id": z.uuid(),
"handle": z.string()
    })

/**
 * @description Successful Response
 */
export const removeMemberV1CampaignsCampaignIdMembersHandleDelete204Schema = z.any()

/**
 * @description Not the campaign\'s owner
 */
export const removeMemberV1CampaignsCampaignIdMembersHandleDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const removeMemberV1CampaignsCampaignIdMembersHandleDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const removeMemberV1CampaignsCampaignIdMembersHandleDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const removeMemberV1CampaignsCampaignIdMembersHandleDeleteMutationResponseSchema = z.lazy(() => removeMemberV1CampaignsCampaignIdMembersHandleDelete204Schema)
