/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const removeBookMonsterV1BooksBookIdMonstersMonsterIdDeletePathParamsSchema = z.object({
    "book_id": z.uuid(),
"monster_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const removeBookMonsterV1BooksBookIdMonstersMonsterIdDelete204Schema = z.any()

/**
 * @description Not the book\'s owner
 */
export const removeBookMonsterV1BooksBookIdMonstersMonsterIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book or content not found
 */
export const removeBookMonsterV1BooksBookIdMonstersMonsterIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const removeBookMonsterV1BooksBookIdMonstersMonsterIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const removeBookMonsterV1BooksBookIdMonstersMonsterIdDeleteMutationResponseSchema = z.lazy(() => removeBookMonsterV1BooksBookIdMonstersMonsterIdDelete204Schema)
