/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { messageResponseSchema } from "./messageResponseSchema.ts";
import { passwordResetRequestSchema } from "./passwordResetRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const requestPasswordResetV1AuthPasswordResetPost202Schema = z.lazy(() => messageResponseSchema).describe("A generic, non-revealing acknowledgement message.")

/**
 * @description Validation Error
 */
export const requestPasswordResetV1AuthPasswordResetPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

/**
 * @description Too many reset requests
 */
export const requestPasswordResetV1AuthPasswordResetPost429Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const requestPasswordResetV1AuthPasswordResetPostMutationRequestSchema = z.lazy(() => passwordResetRequestSchema).describe("Payload to request a password-reset email.\n\n``identifier`` is the account's username or email (same matching as\nlogin). The response is identical whether or not an account matches, so\nit never reveals which addresses are registered.")

export const requestPasswordResetV1AuthPasswordResetPostMutationResponseSchema = z.lazy(() => requestPasswordResetV1AuthPasswordResetPost202Schema)
