/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const resendVerificationV1AuthResendVerificationPost204Schema = z.any()

/**
 * @description Not authenticated
 */
export const resendVerificationV1AuthResendVerificationPost401Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description CSRF token missing or invalid
 */
export const resendVerificationV1AuthResendVerificationPost403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Too many resend attempts
 */
export const resendVerificationV1AuthResendVerificationPost429Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const resendVerificationV1AuthResendVerificationPostMutationResponseSchema = z.lazy(() => resendVerificationV1AuthResendVerificationPost204Schema)
