/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Metadata about a paginated resultset.
 */
export const resultsetMetaSchema = z.object({
    "count": z.int(),
"offset": z.int(),
"limit": z.int()
    }).describe("Metadata about a paginated resultset.")
