/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const revokeInviteV1CampaignsCampaignIdInvitesInviteIdDeletePathParamsSchema = z.object({
    "campaign_id": z.uuid(),
"invite_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const revokeInviteV1CampaignsCampaignIdInvitesInviteIdDelete204Schema = z.any()

/**
 * @description Not the campaign\'s owner
 */
export const revokeInviteV1CampaignsCampaignIdInvitesInviteIdDelete403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const revokeInviteV1CampaignsCampaignIdInvitesInviteIdDelete404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const revokeInviteV1CampaignsCampaignIdInvitesInviteIdDelete422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const revokeInviteV1CampaignsCampaignIdInvitesInviteIdDeleteMutationResponseSchema = z.lazy(() => revokeInviteV1CampaignsCampaignIdInvitesInviteIdDelete204Schema)
