/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Passive perception (required) plus optional special senses.
 */
export const sensesSchema = z.object({
    "passivePerception": z.int(),
"blindsight": z.string().nullish(),
"darkvision": z.string().nullish(),
"tremorsense": z.string().nullish(),
"truesight": z.string().nullish()
    }).catchall(z.any()).describe("Passive perception (required) plus optional special senses.")
