/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to create a new account.
 */
export const signupRequestSchema = z.object({
    "email": z.email(),
"password": z.string().min(8).max(128)
    }).describe("Payload to create a new account.")
