/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { signupRequestSchema } from "./signupRequestSchema.ts";
import { userResponseSchema } from "./userResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const signupV1AuthSignupPost201Schema = z.lazy(() => userResponseSchema).describe("The owner's own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.")

/**
 * @description Username or email already registered
 */
export const signupV1AuthSignupPost409Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const signupV1AuthSignupPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

/**
 * @description Too many signup attempts
 */
export const signupV1AuthSignupPost429Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

export const signupV1AuthSignupPostMutationRequestSchema = z.lazy(() => signupRequestSchema).describe("Payload to create a new account.")

export const signupV1AuthSignupPostMutationResponseSchema = z.lazy(() => signupV1AuthSignupPost201Schema)
