/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Movement speeds. Strings like \'40 ft.\' verbatim from the SRD.
 */
export const speedSchema = z.object({
    "walk": z.string().nullish(),
"fly": z.string().nullish(),
"swim": z.string().nullish(),
"climb": z.string().nullish(),
"burrow": z.string().nullish(),
"hover": z.boolean().nullish()
    }).catchall(z.any()).describe("Movement speeds. Strings like '40 ft.' verbatim from the SRD.")
