/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Full spell details, used in the detail endpoint.
 */
export const spellDetailSchema = z.object({
    "slug": z.string(),
"name": z.string(),
"level": z.string(),
"school": z.nullable(z.string()),
"content": z.object({

    }).catchall(z.any()),
"contentSource": z.object({

    }).catchall(z.any())
    }).describe("Full spell details, used in the detail endpoint.")
