/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { bookMembershipSchema } from "./bookMembershipSchema.ts";
import { contentSourceSchema } from "./contentSourceSchema.ts";
import { srdSpellContentSchema } from "./srdSpellContentSchema.ts";
import { z } from "zod/v4";

/**
 * @description Full spell details, used in the detail endpoint.
 */
export const spellDetailSchema = z.object({
    "slug": z.string().describe("URL-safe unique identifier."),
"name": z.string().describe("The spell's name."),
"level": z.string().describe("Level as a display string (e.g. 'Cantrip', '1st')."),
"school": z.nullable(z.string().describe("School of magic (e.g. 'evocation').")),
get "bookMemberships"(){
                return z.array(bookMembershipSchema.describe("A book owned by the requesting user that contains this content.")).describe("The signed-in user's own books that contain this entry. Present only when requested via include=book_memberships; omitted for anonymous requests.").nullish()
              },
get "content"(){
                return srdSpellContentSchema.describe("SRD spell content payload.")
              },
get "contentSource"(){
                return contentSourceSchema.describe("SRD content source attribution.\n\nAttributes:\n    type: Identifier for the kind of source (e.g. \"srd\").\n    license: Human-readable license name (e.g. \"CC BY 4.0\").\n    license_url: URL to the license text.\n    attribution: Required attribution string per the license.\n    data_provider: Origin of the seed data (e.g. \"5e-bits/5e-database\").\n    data_provider_url: URL to the data provider's source repo.")
              }
    }).describe("Full spell details, used in the detail endpoint.")
