/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { contentSourceSchema } from "./contentSourceSchema.ts";
import { srdSpellContentSchema } from "./srdSpellContentSchema.ts";
import { z } from "zod/v4";

/**
 * @description Full spell details, used in the detail endpoint.
 */
export const spellDetailSchema = z.object({
    "slug": z.string(),
"name": z.string(),
"level": z.string(),
"school": z.nullable(z.string()),
get "content"(){
                return srdSpellContentSchema.describe("SRD spell content payload.")
              },
get "contentSource"(){
                return contentSourceSchema.describe("SRD content source attribution.\n\nAttributes:\n    type: Identifier for the kind of source (e.g. \"srd\").\n    license: Human-readable license name (e.g. \"CC BY 4.0\").\n    license_url: URL to the license text.\n    attribution: Required attribution string per the license.\n    data_provider: Origin of the seed data (e.g. \"5e-bits/5e-database\").\n    data_provider_url: URL to the data provider's source repo.")
              }
    }).describe("Full spell details, used in the detail endpoint.")
