/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Summary info for a spell, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the spell, used in URLs.\n    name: The spell\'s name.\n    level: The spell\'s level as a display string (e.g. \"Cantrip\", \"1st\").\n    school: The spell\'s school of magic (e.g. \"evocation\").
 */
export const spellSummarySchema = z.object({
    "slug": z.string(),
"name": z.string(),
"level": z.string(),
"school": z.nullable(z.string())
    }).describe("Summary info for a spell, used in list endpoints.\n\nAttributes:\n    slug: Unique identifier for the spell, used in URLs.\n    name: The spell's name.\n    level: The spell's level as a display string (e.g. \"Cantrip\", \"1st\").\n    school: The spell's school of magic (e.g. \"evocation\").")
