/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Summary info for a spell, used in list endpoints.
 */
export const spellSummarySchema = z.object({
    "slug": z.string().describe("URL-safe unique identifier."),
"name": z.string().describe("The spell's name."),
"level": z.string().describe("Level as a display string (e.g. 'Cantrip', '1st')."),
"school": z.nullable(z.string().describe("School of magic (e.g. 'evocation')."))
    }).describe("Summary info for a spell, used in list endpoints.")
