/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { armorClassSchema } from "./armorClassSchema.ts";
import { costSchema } from "./costSchema.ts";
import { damageSchema } from "./damageSchema.ts";
import { rangeSchema } from "./rangeSchema.ts";
import { srdReferenceSchema } from "./srdReferenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description SRD item content payload.
 */
export const srdItemContentSchema = z.object({
    "name": z.string(),
"desc": z.array(z.string()).nullish(),
get "cost"(){
                return costSchema.describe("Item cost as a quantity + currency unit (gp, sp, cp, pp, ep).").nullish()
              },
"weight": z.number().nullish(),
"weaponCategory": z.string().nullish(),
"weaponRange": z.string().nullish(),
get "damage"(){
                return damageSchema.describe("Weapon damage roll (dice + optional flat bonus + damage type).").nullish()
              },
get "twoHandedDamage"(){
                return damageSchema.describe("Weapon damage roll (dice + optional flat bonus + damage type).").nullish()
              },
get "properties"(){
                return z.array(srdReferenceSchema.describe("An SRD reference link.")).nullish()
              },
get "range"(){
                return rangeSchema.describe("Weapon range in feet. `long` is omitted on melee weapons.").nullish()
              },
"armorCategory": z.string().nullish(),
get "armorClass"(){
                return armorClassSchema.describe("Armor's base AC plus Dex-bonus rules.").nullish()
              },
"strMinimum": z.int().nullish(),
"stealthDisadvantage": z.boolean().nullish(),
"requiresAttunement": z.string().nullish()
    }).catchall(z.any()).describe("SRD item content payload.")
