/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { actionEntrySchema } from "./actionEntrySchema.ts";
import { armorClassEntrySchema } from "./armorClassEntrySchema.ts";
import { proficiencySchema } from "./proficiencySchema.ts";
import { sensesSchema } from "./sensesSchema.ts";
import { speedSchema } from "./speedSchema.ts";
import { srdReferenceSchema } from "./srdReferenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description SRD monster content payload.
 */
export const srdMonsterContentSchema = z.object({
    "name": z.string(),
"size": z.string(),
"type": z.string(),
"alignment": z.string(),
get "armorClass"(){
                return z.array(armorClassEntrySchema.describe("One element of the AC array (monsters carry multiple AC sources)."))
              },
"hitPoints": z.int(),
"hitDice": z.string(),
"hitPointsRoll": z.string().nullish(),
get "speed"(){
                return speedSchema.describe("Movement speeds. Strings like '40 ft.' verbatim from the SRD.")
              },
"strength": z.int(),
"dexterity": z.int(),
"constitution": z.int(),
"intelligence": z.int(),
"wisdom": z.int(),
"charisma": z.int(),
get "proficiencies"(){
                return z.array(proficiencySchema.describe("A saving-throw or skill proficiency; index on `proficiency.index`."))
              },
"damageImmunities": z.array(z.string()),
"damageResistances": z.array(z.string()),
"damageVulnerabilities": z.array(z.string()),
get "conditionImmunities"(){
                return z.array(srdReferenceSchema.describe("An SRD reference link."))
              },
get "senses"(){
                return sensesSchema.describe("Passive perception (required) plus optional special senses.")
              },
"languages": z.string(),
"challengeRating": z.number(),
"xp": z.int(),
"proficiencyBonus": z.int().nullish(),
get "actions"(){
                return z.array(actionEntrySchema.describe("An action-shaped entry (actions, special_abilities, reactions, etc.).\n\nWe render `name` + `desc`; everything else (damage, dc, usage,\nattack_bonus, ...) flows through via extra='allow'."))
              },
get "specialAbilities"(){
                return z.array(actionEntrySchema.describe("An action-shaped entry (actions, special_abilities, reactions, etc.).\n\nWe render `name` + `desc`; everything else (damage, dc, usage,\nattack_bonus, ...) flows through via extra='allow'."))
              },
get "reactions"(){
                return z.array(actionEntrySchema.describe("An action-shaped entry (actions, special_abilities, reactions, etc.).\n\nWe render `name` + `desc`; everything else (damage, dc, usage,\nattack_bonus, ...) flows through via extra='allow'.")).nullish()
              },
get "legendaryActions"(){
                return z.array(actionEntrySchema.describe("An action-shaped entry (actions, special_abilities, reactions, etc.).\n\nWe render `name` + `desc`; everything else (damage, dc, usage,\nattack_bonus, ...) flows through via extra='allow'.")).nullish()
              }
    }).catchall(z.any()).describe("SRD monster content payload.")
