/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description An SRD reference link.
 */
export const srdReferenceSchema = z.object({
    "index": z.string(),
"name": z.string(),
"url": z.string().nullish()
    }).catchall(z.any()).describe("An SRD reference link.")
