/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { srdReferenceSchema } from "./srdReferenceSchema.ts";
import { z } from "zod/v4";

/**
 * @description SRD spell content payload.
 */
export const srdSpellContentSchema = z.object({
    "name": z.string(),
"level": z.int(),
get "school"(){
                return srdReferenceSchema.describe("An SRD reference link.")
              },
"castingTime": z.string(),
"range": z.string(),
"components": z.array(z.string()),
"material": z.string().nullish(),
"duration": z.string(),
"concentration": z.boolean(),
"ritual": z.boolean().nullish(),
"desc": z.array(z.string()),
"higherLevel": z.array(z.string()).nullish(),
get "classes"(){
                return z.array(srdReferenceSchema.describe("An SRD reference link.")).nullish()
              }
    }).catchall(z.any()).describe("SRD spell content payload.")
