/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { campaignDetailSchema } from "./campaignDetailSchema.ts";
import { campaignUpdateSchema } from "./campaignUpdateSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const updateCampaignV1CampaignsCampaignIdPatchPathParamsSchema = z.object({
    "campaign_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const updateCampaignV1CampaignsCampaignIdPatch200Schema = z.lazy(() => campaignDetailSchema).describe("A single campaign with its member and enabled-book counts.")

/**
 * @description Not the campaign\'s owner
 */
export const updateCampaignV1CampaignsCampaignIdPatch403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Campaign not found
 */
export const updateCampaignV1CampaignsCampaignIdPatch404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const updateCampaignV1CampaignsCampaignIdPatch422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const updateCampaignV1CampaignsCampaignIdPatchMutationRequestSchema = z.lazy(() => campaignUpdateSchema).describe("Payload to update a campaign. Only the provided fields are changed.")

export const updateCampaignV1CampaignsCampaignIdPatchMutationResponseSchema = z.lazy(() => updateCampaignV1CampaignsCampaignIdPatch200Schema)
