/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { bookDetailSchema } from "./bookDetailSchema.ts";
import { bookUpdateSchema } from "./bookUpdateSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { z } from "zod/v4";

export const updateBookV1BooksBookIdPatchPathParamsSchema = z.object({
    "book_id": z.uuid()
    })

/**
 * @description Successful Response
 */
export const updateBookV1BooksBookIdPatch200Schema = z.lazy(() => bookDetailSchema).describe("A single book with the count of content it holds, by resource type.")

/**
 * @description Not the book\'s owner
 */
export const updateBookV1BooksBookIdPatch403Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Book not found
 */
export const updateBookV1BooksBookIdPatch404Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const updateBookV1BooksBookIdPatch422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const updateBookV1BooksBookIdPatchMutationRequestSchema = z.lazy(() => bookUpdateSchema).describe("Payload to update a book. Only the provided fields are changed.")

export const updateBookV1BooksBookIdPatchMutationResponseSchema = z.lazy(() => updateBookV1BooksBookIdPatch200Schema)
