/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Public representation of a user; never includes the password hash.
 */
export const userResponseSchema = z.object({
    "id": z.uuid(),
"email": z.email(),
"emailVerified": z.boolean(),
"createdAt": z.iso.datetime()
    }).describe("Public representation of a user; never includes the password hash.")
