/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description The owner\'s own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.
 */
export const userResponseSchema = z.object({
    "id": z.uuid(),
"username": z.string(),
"email": z.email(),
"emailVerified": z.boolean(),
"createdAt": z.iso.datetime()
    }).describe("The owner's own view of their account.\n\nReturned only to the authenticated account holder (signup, login,\n``/me``). ``email`` appears here and nowhere else; other users see the\n``Author`` projection instead.")
