/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { errorResponseSchema } from "./errorResponseSchema.ts";
import { verifyEmailRequestSchema } from "./verifyEmailRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description Successful Response
 */
export const verifyEmailV1AuthVerifyEmailPost204Schema = z.any()

/**
 * @description Token is invalid or expired
 */
export const verifyEmailV1AuthVerifyEmailPost400Schema = z.lazy(() => errorResponseSchema).describe("Standard error response schema.")

/**
 * @description Validation Error
 */
export const verifyEmailV1AuthVerifyEmailPost422Schema = z.lazy(() => HTTPValidationErrorSchema)

export const verifyEmailV1AuthVerifyEmailPostMutationRequestSchema = z.lazy(() => verifyEmailRequestSchema).describe("Payload to confirm an email address with a verification token.")

export const verifyEmailV1AuthVerifyEmailPostMutationResponseSchema = z.lazy(() => verifyEmailV1AuthVerifyEmailPost204Schema)
