/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Payload to confirm an email address with a verification token.
 */
export const verifyEmailRequestSchema = z.object({
    "token": z.string().min(1)
    }).describe("Payload to confirm an email address with a verification token.")
