/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return API status and current version.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Create a new account, start a session, and send a verification email.
         *
         *     Args:
         *         payload: Username, email, and password for the new account.
         *         response: Response used to set the session and CSRF cookies.
         *         db: Database session.
         *         background_tasks: Used to send the verification email off the
         *             response path.
         *
         *     Returns:
         *         The created user (with ``email_verified`` false until they confirm).
         *
         *     Raises:
         *         AppError: 409 if the username or email is already registered.
         */
        post: operations["signup_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Authenticate with a username-or-email and password, start a session.
         *
         *     The ``identifier`` is matched against email when it contains ``@`` and
         *     against username otherwise; both lookups are case-insensitive since both
         *     fields are stored lowercase.
         *
         *     Args:
         *         payload: Identifier (username or email) and password.
         *         response: Response used to set the session and CSRF cookies.
         *         db: Database session.
         *
         *     Returns:
         *         The authenticated user.
         *
         *     Raises:
         *         AppError: 401 if the identifier or password is incorrect.
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revoke the current session (or all the user's) and clear cookies.
         *
         *     Args:
         *         request: Request carrying the session cookie.
         *         response: Response used to clear the cookies.
         *         db: Database session.
         *         user: The authenticated user; also enforces a valid session.
         *         everywhere: When true, revoke every session for the user.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user
         * @description Return the currently authenticated user.
         *
         *     Args:
         *         user: The authenticated user, resolved from the session cookie.
         *
         *     Returns:
         *         The current user.
         */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email address
         * @description Mark a user's email as verified using a verification token.
         *
         *     Unauthenticated: possession of the emailed token is the proof. The token
         *     is single-use; any siblings are retired on success.
         *
         *     Args:
         *         payload: The verification token.
         *         db: Database session.
         *
         *     Raises:
         *         AppError: 400 if the token is invalid, expired, or already used.
         */
        post: operations["verify_email_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the verification email
         * @description Send a fresh verification email to the signed-in user.
         *
         *     A no-op (still ``204``) when the account is already verified. Takes no
         *     email input, so it cannot be used to probe account existence.
         *
         *     Args:
         *         db: Database session.
         *         user: The authenticated user.
         *         background_tasks: Used to send the email off the response path.
         */
        post: operations["resend_verification_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset
         * @description Email a password-reset link if the identifier matches an account.
         *
         *     The response is identical whether or not an account matched, so it never
         *     discloses which usernames or emails are registered.
         *
         *     Args:
         *         payload: The account's username or email.
         *         db: Database session.
         *         background_tasks: Used to send the email off the response path.
         *
         *     Returns:
         *         A generic acknowledgement, regardless of whether an account matched.
         */
        post: operations["request_password_reset_v1_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with a reset token
         * @description Set a new password using a reset token and sign the user out.
         *
         *     On success the password is rehashed, every reset token is retired, and
         *     all of the user's sessions are revoked so a thief who held an old session
         *     is locked out. Receiving the reset email proves control of the address,
         *     so an unverified account is verified at the same time. Does not log the
         *     user in; they sign in fresh with the new password.
         *
         *     Args:
         *         payload: The reset token and the new password.
         *         db: Database session.
         *
         *     Raises:
         *         AppError: 400 if the token is invalid, expired, or already used.
         */
        post: operations["confirm_password_reset_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books
         * @description List the user's own books plus the public system books.
         *
         *     Args:
         *         request: Current request, used to build pagination links.
         *         db: Database session.
         *         user: The authenticated user.
         *         params: Pagination parameters.
         *         ordering: SQLAlchemy ordering expressions, injected by dependency.
         *         search: Parsed search filter over name and description.
         *
         *     Returns:
         *         A paginated resultset of book summaries.
         */
        get: operations["list_books_v1_books_get"];
        put?: never;
        /**
         * Create a book
         * @description Create a new, empty book owned by the current user.
         *
         *     Args:
         *         payload: The new book's name and optional description.
         *         db: Database session.
         *         user: The authenticated user, who becomes the owner.
         *
         *     Returns:
         *         The created book (empty, so all content counts are zero).
         */
        post: operations["create_book_v1_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a book
         * @description Return a single book the user may read, with content counts.
         *
         *     Args:
         *         book_id: The book's id.
         *         db: Database session.
         *         user: The authenticated user.
         *
         *     Returns:
         *         The book detail.
         *
         *     Raises:
         *         AppError: 404 if the book does not exist or is not readable.
         */
        get: operations["get_book_v1_books__book_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a book
         * @description Delete a book and its content memberships (owner-only).
         *
         *     The content itself is untouched; only the collection and its join
         *     rows are removed (FK cascade).
         *
         *     Args:
         *         book_id: The book's id.
         *         db: Database session.
         *         user: The authenticated user, who must own the book.
         *
         *     Raises:
         *         AppError: 404 if not readable, 403 if not the user's to delete.
         */
        delete: operations["delete_book_v1_books__book_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a book
         * @description Update a book's name and/or description (owner-only).
         *
         *     Args:
         *         book_id: The book's id.
         *         payload: Fields to change; only provided fields are applied.
         *         db: Database session.
         *         user: The authenticated user, who must own the book.
         *
         *     Returns:
         *         The updated book detail.
         *
         *     Raises:
         *         AppError: 404 if not readable, 403 if not the user's to change.
         */
        patch: operations["update_book_v1_books__book_id__patch"];
        trace?: never;
    };
    "/v1/books/{book_id}/monsters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a book's monsters
         * @description List the monsters in a readable book.
         */
        get: operations["list_book_monsters_v1_books__book_id__monsters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}/monsters/{monster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add a monster to a book
         * @description Add a monster to a book the user owns (idempotent).
         */
        put: operations["add_book_monster_v1_books__book_id__monsters__monster_id__put"];
        post?: never;
        /**
         * Remove a monster from a book
         * @description Remove a monster from a book the user owns (idempotent).
         */
        delete: operations["remove_book_monster_v1_books__book_id__monsters__monster_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a book's spells
         * @description List the spells in a readable book.
         */
        get: operations["list_book_spells_v1_books__book_id__spells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}/spells/{spell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add a spell to a book
         * @description Add a spell to a book the user owns (idempotent).
         */
        put: operations["add_book_spell_v1_books__book_id__spells__spell_id__put"];
        post?: never;
        /**
         * Remove a spell from a book
         * @description Remove a spell from a book the user owns (idempotent).
         */
        delete: operations["remove_book_spell_v1_books__book_id__spells__spell_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a book's items
         * @description List the items in a readable book.
         */
        get: operations["list_book_items_v1_books__book_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{book_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add an item to a book
         * @description Add an item to a book the user owns (idempotent).
         */
        put: operations["add_book_item_v1_books__book_id__items__item_id__put"];
        post?: never;
        /**
         * Remove an item from a book
         * @description Remove an item from a book the user owns (idempotent).
         */
        delete: operations["remove_book_item_v1_books__book_id__items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List items
         * @description Return a paginated list of items with optional filters.
         *
         *     Args:
         *         request: Current HTTP request, used to build pagination links.
         *         session: Database session, injected by dependency.
         *         params: Pagination parameters, injected by dependency.
         *         ordering: SQLAlchemy ordering expressions, injected by dependency.
         *         search: Parsed search filter, injected by dependency.
         *         item_category: Optional exact match for the item_category field.
         *         rarity: Optional exact match for the rarity field. Set to 'none' to
         *             filter for items with no rarity (equipment).
         *
         *     Returns:
         *         A paginated list of items matching the filters, with summary information
         *         and pagination metadata.
         *
         *     Example:
         *         GET /v1/items?search=sword&item_category=weapon&rarity=rare&limit=2
         *         GET /v1/items?item_category=potion&rarity=none
         *         GET /v1/items?order_by=name:asc&limit=5&offset=10
         *         GET /v1/items?order_by=rarity:desc,name:asc
         */
        get: operations["list_items_v1_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/items/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get item details
         * @description Return full details for a single item by slug and namespace.
         *
         *     Args:
         *         slug: The unique slug identifier for the item.
         *         session: Database session, injected by dependency.
         *         namespace: The source namespace to look up the item in.
         *
         *     Returns:
         *         The full details of the item, including all original content fields.
         *
         *     Raises:
         *         AppError: With status 404 if no item is found.
         *
         *     Example:
         *         GET /v1/items/flame-tongue?namespace=srd-5.1
         *         GET /v1/items/amulet-of-health?namespace=user:1234
         */
        get: operations["get_item_v1_items__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monsters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List monsters
         * @description Return a paginated list of monsters with optional filters.
         *
         *     Args:
         *         request: Current HTTP request, used to build pagination links.
         *         session: Database session, injected by dependency.
         *         params: Pagination parameters, injected by dependency.
         *         ordering: SQLAlchemy ordering expressions, injected by dependency.
         *         search: Parsed search filter, injected by dependency.
         *         monster_type: Optional exact match for the monster_type field.
         *         cr_min: Inclusive minimum challenge rating filter.
         *         cr_max: Inclusive maximum challenge rating filter.
         *
         *     Returns:
         *         A paginated resultset containing monster summaries and pagination
         *         metadata.
         *
         *     Example:
         *         GET /v1/monsters?search=dragon&limit=5&offset=10
         *         GET /v1/monsters?type=undead&cr_min=1&cr_max=5
         *         GET /v1/monsters?cr_max=0.25&order_by=name:asc
         *         GET /v1/monsters?order_by=challenge_rating:desc,name:asc
         */
        get: operations["list_monsters_v1_monsters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/monsters/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get monster
         * @description Return full details for a single monster by slug.
         *
         *     Args:
         *         slug: The URL-safe unique identifier for the monster.
         *         session: Database session, injected by dependency.
         *         namespace: The source namespace to look in (default: srd-5.1).
         *
         *     Returns:
         *         The full monster details, including all original content fields.
         *
         *     Raises:
         *         AppError: With status 404 if no monster is found.
         *
         *     Example:
         *         GET /v1/monsters/tarrasque
         *         GET /v1/monsters/giant-spider?namespace=user:1234
         */
        get: operations["get_monster_v1_monsters__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List spells
         * @description Return a paginated list of spells with optional filters.
         *
         *     Args:
         *         request: Current HTTP request, used to build pagination links.
         *         session: Database session, injected by dependency.
         *         params: Pagination parameters, injected by dependency.
         *         ordering: SQLAlchemy ordering expressions, injected by dependency.
         *         search: Parsed search filter, injected by dependency.
         *         school: Optional exact match for spell school.
         *         level_min: Optional minimum spell level (inclusive).
         *         level_max: Optional maximum spell level (inclusive).
         *
         *     Returns:
         *         A paginated resultset containing spell summaries that match the
         *         provided filters.
         *
         *     Example:
         *         GET /v1/spells?search=fire&level_min=1&level_max=3&school=evocation
         *         GET /v1/spells?level_max=0
         *         GET /v1/spells?order_by=name:asc
         *         GET /v1/spells?order_by=level:desc,name:asc&limit=5&offset=10
         */
        get: operations["list_spells_v1_spells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/spells/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get spell
         * @description Return full details for a single spell by slug.
         *
         *     Args:
         *         slug: The URL-safe unique identifier for the spell.
         *         session: Database session, injected by dependency.
         *         namespace: The source namespace to look in (default: srd-5.1).
         *
         *     Returns:
         *         The full spell details, including all original content fields.
         *
         *     Raises:
         *         AppError: With status 404 if no spell is found.
         *
         *     Example:
         *         GET /v1/spells/fireball
         *         GET /v1/spells/fireball?namespace=user:1234
         */
        get: operations["get_spell_v1_spells__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionEntry
         * @description An action-shaped entry (actions, special_abilities, reactions, etc.).
         *
         *     We render `name` + `desc`; everything else (damage, dc, usage,
         *     attack_bonus, ...) flows through via extra='allow'.
         */
        ActionEntry: {
            /** Name */
            name: string;
            /** Desc */
            desc: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ArmorClass
         * @description Armor's base AC plus Dex-bonus rules.
         */
        ArmorClass: {
            /** Base */
            base: number;
            /** Dexbonus */
            dexBonus: boolean;
            /** Maxbonus */
            maxBonus?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ArmorClassEntry
         * @description One element of the AC array (monsters carry multiple AC sources).
         */
        ArmorClassEntry: {
            /** Type */
            type: string;
            /** Value */
            value: number;
            /** Condition */
            condition?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * Author
         * @description Public author projection -- how a user is shown to *other* users.
         *
         *     The only user data exposed when homebrew is published (#185, consumed by
         *     #177+). Deliberately carries ``username`` alone: it is a unique,
         *     immutable, stable public handle in Phase 1b, so neither the private
         *     email nor the internal user id ever needs to leave the owner's own view.
         *     Adding fields later (e.g. a stable public id, should usernames ever
         *     become mutable) is an additive, non-breaking change.
         */
        Author: {
            /** Username */
            username: string;
        };
        /**
         * BookCreate
         * @description Payload to create a book.
         */
        BookCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * BookDetail
         * @description A single book with the count of content it holds, by resource type.
         */
        BookDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string | null;
            /** Description */
            description: string | null;
            /** Ispublic */
            isPublic: boolean;
            /** Issystem */
            isSystem: boolean;
            owner: components["schemas"]["Author"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Monstercount */
            monsterCount: number;
            /** Spellcount */
            spellCount: number;
            /** Itemcount */
            itemCount: number;
        };
        /**
         * BookSummary
         * @description A book as shown in list views.
         *
         *     ``owner`` is the public author projection (username only) for a
         *     user-owned book, or null for a system book such as the SRD catalog.
         *     ``isSystem`` books are read-only; ``isPublic`` books are readable by
         *     anyone.
         */
        BookSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string | null;
            /** Description */
            description: string | null;
            /** Ispublic */
            isPublic: boolean;
            /** Issystem */
            isSystem: boolean;
            owner: components["schemas"]["Author"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * BookUpdate
         * @description Payload to update a book. Only the provided fields are changed.
         */
        BookUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * ContentSource
         * @description SRD content source attribution.
         *
         *     Attributes:
         *         type: Identifier for the kind of source (e.g. "srd").
         *         license: Human-readable license name (e.g. "CC BY 4.0").
         *         license_url: URL to the license text.
         *         attribution: Required attribution string per the license.
         *         data_provider: Origin of the seed data (e.g. "5e-bits/5e-database").
         *         data_provider_url: URL to the data provider's source repo.
         */
        ContentSource: {
            /** Type */
            type: string;
            /** License */
            license: string;
            /** Licenseurl */
            licenseUrl: string;
            /** Attribution */
            attribution: string;
            /** Dataprovider */
            dataProvider: string;
            /** Dataproviderurl */
            dataProviderUrl: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Cost
         * @description Item cost as a quantity + currency unit (gp, sp, cp, pp, ep).
         */
        Cost: {
            /** Quantity */
            quantity: number;
            /** Unit */
            unit: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Damage
         * @description Weapon damage roll (dice + optional flat bonus + damage type).
         */
        Damage: {
            /** Damagedice */
            damageDice: string;
            /** Damagebonus */
            damageBonus?: number | null;
            damageType: components["schemas"]["SrdReference"];
        } & {
            [key: string]: unknown;
        };
        /**
         * ErrorResponse
         * @description Standard error response schema.
         */
        ErrorResponse: {
            /** Status */
            status: number;
            /** Developermessage */
            developerMessage: string;
            /** Usermessage */
            userMessage: string;
            /** Errorcode */
            errorCode: string;
            /** Moreinfo */
            moreInfo: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response schema for the health check endpoint.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * ItemDetail
         * @description Full item details, used in detail endpoints.
         *
         *     Attributes:
         *         content: The full item data as ingested from the source, with all
         *             original fields and structure preserved.
         *         content_source: Metadata about the source of the item data, such as
         *             the original URL or source file name.
         */
        ItemDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Itemcategory */
            itemCategory: string | null;
            /** Rarity */
            rarity: string | null;
            content: components["schemas"]["SrdItemContent"];
            contentSource: components["schemas"]["ContentSource"];
        };
        /**
         * ItemSummary
         * @description Summary info for an item, used in list endpoints.
         *
         *     Attributes:
         *         slug: Unique identifier for the item, used in URLs.
         *         name: The item's name.
         *         item_category: The category of the item (e.g. "Weapon", "Potion"),
         *             if available. This is not guaranteed to be present for all items, as
         *             it depends on the source data.
         *         rarity: The rarity of the item (e.g. "Common", "Rare"), if available.
         */
        ItemSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Itemcategory */
            itemCategory: string | null;
            /** Rarity */
            rarity: string | null;
        };
        /**
         * Links
         * @description Prev/next navigation links for a paginated resultset.
         *
         *     Attributes:
         *         prev: Absolute URL for the previous page, or null on the first page.
         *         next: Absolute URL for the next page, or null on the last page.
         */
        Links: {
            /** Prev */
            prev: string | null;
            /** Next */
            next: string | null;
        };
        /**
         * LoginRequest
         * @description Payload to authenticate with a username-or-email and password.
         *
         *     ``identifier`` accepts either the account's username or its email; the
         *     presence of ``@`` disambiguates (usernames cannot contain ``@``).
         */
        LoginRequest: {
            /** Identifier */
            identifier: string;
            /** Password */
            password: string;
        };
        /**
         * MessageResponse
         * @description A generic, non-revealing acknowledgement message.
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * MetadataEnvelope
         * @description Envelopes a paginated resultset with metadata.
         */
        MetadataEnvelope: {
            resultset: components["schemas"]["ResultsetMeta"];
            links: components["schemas"]["Links"];
        };
        /**
         * MonsterDetail
         * @description Full monster details, used in detail endpoints.
         *
         *     Attributes:
         *         content: The full monster data as ingested from the source, with all
         *             original fields and structure preserved.
         *         content_source: Metadata about the source of the monster data, such as
         *             the original URL or source file name.
         */
        MonsterDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Monstertype */
            monsterType: string | null;
            /** Challengerating */
            challengeRating: string;
            content: components["schemas"]["SrdMonsterContent"];
            contentSource: components["schemas"]["ContentSource"];
        };
        /**
         * MonsterSummary
         * @description Summary info for a monster, used in list endpoints.
         *
         *     Attributes:
         *         slug: Unique identifier for the monster, used in URLs.
         *         name: The monster's name.
         *         monster_type: The type or category of the monster (e.g. "Dragon").
         *         challenge_rating: The monster's challenge rating as a display string
         *             (e.g. "1/2", "5", "10").
         */
        MonsterSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Monstertype */
            monsterType: string | null;
            /** Challengerating */
            challengeRating: string;
        };
        /** PaginatedResultset[BookSummary] */
        PaginatedResultset_BookSummary_: {
            metadata: components["schemas"]["MetadataEnvelope"];
            /** Data */
            data: components["schemas"]["BookSummary"][];
        };
        /** PaginatedResultset[ItemSummary] */
        PaginatedResultset_ItemSummary_: {
            metadata: components["schemas"]["MetadataEnvelope"];
            /** Data */
            data: components["schemas"]["ItemSummary"][];
        };
        /** PaginatedResultset[MonsterSummary] */
        PaginatedResultset_MonsterSummary_: {
            metadata: components["schemas"]["MetadataEnvelope"];
            /** Data */
            data: components["schemas"]["MonsterSummary"][];
        };
        /** PaginatedResultset[SpellSummary] */
        PaginatedResultset_SpellSummary_: {
            metadata: components["schemas"]["MetadataEnvelope"];
            /** Data */
            data: components["schemas"]["SpellSummary"][];
        };
        /**
         * PasswordResetConfirmRequest
         * @description Payload to set a new password using a reset token.
         */
        PasswordResetConfirmRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * PasswordResetRequest
         * @description Payload to request a password-reset email.
         *
         *     ``identifier`` is the account's username or email (same matching as
         *     login). The response is identical whether or not an account matches, so
         *     it never reveals which addresses are registered.
         */
        PasswordResetRequest: {
            /** Identifier */
            identifier: string;
        };
        /**
         * Proficiency
         * @description A saving-throw or skill proficiency; index on `proficiency.index`.
         */
        Proficiency: {
            /** Value */
            value: number;
            proficiency: components["schemas"]["SrdReference"];
        } & {
            [key: string]: unknown;
        };
        /**
         * Range
         * @description Weapon range in feet. `long` is omitted on melee weapons.
         */
        Range: {
            /** Normal */
            normal: number;
            /** Long */
            long?: number | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ResultsetMeta
         * @description Metadata about a paginated resultset.
         */
        ResultsetMeta: {
            /** Count */
            count: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * Senses
         * @description Passive perception (required) plus optional special senses.
         */
        Senses: {
            /** Passiveperception */
            passivePerception: number;
            /** Blindsight */
            blindsight?: string | null;
            /** Darkvision */
            darkvision?: string | null;
            /** Tremorsense */
            tremorsense?: string | null;
            /** Truesight */
            truesight?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SignupRequest
         * @description Payload to create a new account.
         */
        SignupRequest: {
            /**
             * Username
             * @description Public handle. Lowercase letters, digits, hyphen, and underscore only; 3-30 characters.
             */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Speed
         * @description Movement speeds. Strings like '40 ft.' verbatim from the SRD.
         */
        Speed: {
            /** Walk */
            walk?: string | null;
            /** Fly */
            fly?: string | null;
            /** Swim */
            swim?: string | null;
            /** Climb */
            climb?: string | null;
            /** Burrow */
            burrow?: string | null;
            /** Hover */
            hover?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SpellDetail
         * @description Full spell details, used in the detail endpoint.
         */
        SpellDetail: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Level */
            level: string;
            /** School */
            school: string | null;
            content: components["schemas"]["SrdSpellContent"];
            contentSource: components["schemas"]["ContentSource"];
        };
        /**
         * SpellSummary
         * @description Summary info for a spell, used in list endpoints.
         *
         *     Attributes:
         *         slug: Unique identifier for the spell, used in URLs.
         *         name: The spell's name.
         *         level: The spell's level as a display string (e.g. "Cantrip", "1st").
         *         school: The spell's school of magic (e.g. "evocation").
         */
        SpellSummary: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Level */
            level: string;
            /** School */
            school: string | null;
        };
        /**
         * SrdItemContent
         * @description SRD item content payload.
         */
        SrdItemContent: {
            /** Name */
            name: string;
            /** Desc */
            desc?: string[] | null;
            cost?: components["schemas"]["Cost"];
            /** Weight */
            weight?: number | null;
            /** Weaponcategory */
            weaponCategory?: string | null;
            /** Weaponrange */
            weaponRange?: string | null;
            damage?: components["schemas"]["Damage"];
            twoHandedDamage?: components["schemas"]["Damage"];
            /** Properties */
            properties?: components["schemas"]["SrdReference"][] | null;
            range?: components["schemas"]["Range"];
            /** Armorcategory */
            armorCategory?: string | null;
            armorClass?: components["schemas"]["ArmorClass"];
            /** Strminimum */
            strMinimum?: number | null;
            /** Stealthdisadvantage */
            stealthDisadvantage?: boolean | null;
            /** Requiresattunement */
            requiresAttunement?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SrdMonsterContent
         * @description SRD monster content payload.
         */
        SrdMonsterContent: {
            /** Name */
            name: string;
            /** Size */
            size: string;
            /** Type */
            type: string;
            /** Alignment */
            alignment: string;
            /** Armorclass */
            armorClass: components["schemas"]["ArmorClassEntry"][];
            /** Hitpoints */
            hitPoints: number;
            /** Hitdice */
            hitDice: string;
            /** Hitpointsroll */
            hitPointsRoll?: string | null;
            speed: components["schemas"]["Speed"];
            /** Strength */
            strength: number;
            /** Dexterity */
            dexterity: number;
            /** Constitution */
            constitution: number;
            /** Intelligence */
            intelligence: number;
            /** Wisdom */
            wisdom: number;
            /** Charisma */
            charisma: number;
            /** Proficiencies */
            proficiencies: components["schemas"]["Proficiency"][];
            /** Damageimmunities */
            damageImmunities: string[];
            /** Damageresistances */
            damageResistances: string[];
            /** Damagevulnerabilities */
            damageVulnerabilities: string[];
            /** Conditionimmunities */
            conditionImmunities: components["schemas"]["SrdReference"][];
            senses: components["schemas"]["Senses"];
            /** Languages */
            languages: string;
            /** Challengerating */
            challengeRating: number;
            /** Xp */
            xp: number;
            /** Proficiencybonus */
            proficiencyBonus?: number | null;
            /** Actions */
            actions: components["schemas"]["ActionEntry"][];
            /** Specialabilities */
            specialAbilities: components["schemas"]["ActionEntry"][];
            /** Reactions */
            reactions?: components["schemas"]["ActionEntry"][] | null;
            /** Legendaryactions */
            legendaryActions?: components["schemas"]["ActionEntry"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SrdReference
         * @description An SRD reference link.
         */
        SrdReference: {
            /** Index */
            index: string;
            /** Name */
            name: string;
            /** Url */
            url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SrdSpellContent
         * @description SRD spell content payload.
         */
        SrdSpellContent: {
            /** Name */
            name: string;
            /** Level */
            level: number;
            school: components["schemas"]["SrdReference"];
            /** Castingtime */
            castingTime: string;
            /** Range */
            range: string;
            /** Components */
            components: string[];
            /** Material */
            material?: string | null;
            /** Duration */
            duration: string;
            /** Concentration */
            concentration: boolean;
            /** Ritual */
            ritual?: boolean | null;
            /** Desc */
            desc: string[];
            /** Higherlevel */
            higherLevel?: string[] | null;
            /** Classes */
            classes?: components["schemas"]["SrdReference"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UserResponse
         * @description The owner's own view of their account.
         *
         *     Returned only to the authenticated account holder (signup, login,
         *     ``/me``). ``email`` appears here and nowhere else; other users see the
         *     ``Author`` projection instead.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Emailverified */
            emailVerified: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerifyEmailRequest
         * @description Payload to confirm an email address with a verification token.
         */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    signup_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Username or email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many signup attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many login attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: {
                /** @description Revoke all of this user's sessions, not just this. */
                everywhere?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verify_email_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token is invalid or expired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description CSRF token missing or invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many resend attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    request_password_reset_v1_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many reset requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_password_reset_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token is invalid or expired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_books_v1_books_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: created_at, name, updated_at. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name, description. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_BookSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_book_v1_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_v1_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_v1_books__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_book_v1_books__book_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_book_monsters_v1_books__book_id__monsters_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: challenge_rating, monster_type, name. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name, monster_type. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_MonsterSummary_"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_monster_v1_books__book_id__monsters__monster_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_monster_v1_books__book_id__monsters__monster_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_book_spells_v1_books__book_id__spells_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: level, name, school. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_SpellSummary_"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_spell_v1_books__book_id__spells__spell_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                spell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_spell_v1_books__book_id__spells__spell_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                spell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_book_items_v1_books__book_id__items_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: item_category, name, rarity. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name, item_category. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_ItemSummary_"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_item_v1_books__book_id__items__item_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_item_v1_books__book_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the book's owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Book or content not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_v1_items_get: {
        parameters: {
            query?: {
                /** @description Exact match on item category (e.g. 'weapon'). This is not guaranteed to be present for all items, as it depends on the source data. */
                item_category?: string | null;
                /** @description Exact match on item rarity (e.g. 'common'). This is not guaranteed to be present for all items, as it depends on the source data. Set to 'none' to filter for items with no rarity (equipment). */
                rarity?: string | null;
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: item_category, name, rarity. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name, item_category. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_ItemSummary_"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_item_v1_items__slug__get: {
        parameters: {
            query?: {
                /** @description The source namespace of the item, used to disambiguate items with the same slug from different sources. Known values: 'srd-5.1', 'srd-2024', 'user:{user_id}'. */
                namespace?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetail"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_monsters_v1_monsters_get: {
        parameters: {
            query?: {
                /** @description Exact match on monster type (e.g. 'undead'). */
                type?: string | null;
                /** @description Inclusive minimum challenge rating. */
                cr_min?: (number | string) | null;
                /** @description Inclusive maximum challenge rating. */
                cr_max?: (number | string) | null;
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: challenge_rating, monster_type, name. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name, monster_type. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_MonsterSummary_"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_monster_v1_monsters__slug__get: {
        parameters: {
            query?: {
                /** @description Source namespace to search in. Defaults to the SRD 5.1 namespace. Use 'user:{user_id}' for homebrew content. */
                namespace?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterDetail"];
                };
            };
            /** @description Monster not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spells_v1_spells_get: {
        parameters: {
            query?: {
                /** @description Exact match on spell school (e.g. 'evocation'). */
                school?: string | null;
                /** @description Inclusive minimum spell level (0-9). */
                level_min?: number | null;
                /** @description Inclusive maximum spell level (0-9). */
                level_max?: number | null;
                limit?: number;
                offset?: number;
                /** @description Comma-separated sort fields in column:direction format. Direction is 'asc' or 'desc' (case-insensitive); omitting direction defaults to 'asc'. Valid columns: level, name, school. */
                order_by?: string | null;
                /** @description Case-insensitive substring search. Matches against name. Results are relevance-ordered: earlier columns rank higher than later ones. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResultset_SpellSummary_"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_spell_v1_spells__slug__get: {
        parameters: {
            query?: {
                /** @description Source namespace to search in. Defaults to the SRD 5.1 namespace. Use 'user:{user_id}' for homebrew content. */
                namespace?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpellDetail"];
                };
            };
            /** @description Spell not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
